// Databáza ulíc slovenských miest — z OpenStreetMap
// Organizované podľa miest, mapované na lokality

export interface StreetEntry {
  street: string;
  lokalita: string;
  city: string;
}

// City → streets mapping
const CITY_STREETS: Record<string, string[]> = {
  "Banská Bystrica": [
    "29. augusta", "9. mája", "Achátová", "Agátová", "Alexandra Matušku",
    "Ametystová", "Astrová", "Azalková", "Bagarova", "Bakossova",
    "Bellušova", "Bernolákova", "Beskydská", "Borievková", "Borovicová",
    "Borová", "Bočná", "Boženy Němcovej", "Brestová", "Brezová",
    "Bronzová", "Buková", "Bučinová", "Cementárenská cesta", "Cesta k Smrečine",
    "Cesta k nemocnici", "Cesta na amfiteáter", "Cesta na štadión", "Cesta olympionikov", "Chabenecká",
    "Cintorínska", "Cmárovo", "Cínová", "Dedinská", "Diamantová",
    "Dlhá", "Dobšinského", "Dolná", "Dolná Strieborná", "Dolomitová",
    "Drienková", "Družby", "Družstevná", "Dubová", "Durhamská",
    "Dúhová", "F. Švantnera", "Fatranská", "Figuša Bystrého", "Fraňa Kráľa",
    "Garbanka", "Gaštanová", "Gerberová", "Gerlachovská", "Golianova",
    "Gorkého", "Grafitová", "Harmanecká cesta", "Havranské", "Haškova",
    "Hečkova", "Hlboká", "Horná", "Horná Strieborná", "Horné záhrady",
    "Hronská", "Hronské predmestie", "Hrušková", "Hurbanova", "Hutná",
    "Hviezdoslavova", "Iliašska cesta", "Inovecká", "Internátna", "J. Cikkera",
    "Jabloňová", "Jakubská cesta", "Janka Kráľa", "Jantárová", "Jarná",
    "Jaseňová", "Jaspisová", "Javornícka", "Javorová", "Jazmínová",
    "Jedľová", "Jegorovova", "Jelšová", "Jesenná", "Jesenského",
    "Jilemnického", "Jiráskova", "Jozefa Mistríka", "Jána Bottu", "Jána Chalupku",
    "K Lomu", "Kalcitová", "Kalinčiakova", "Kapitulská", "Kapitána Jaroša",
    "Kapitána Nálepku", "Karola Kuzmányho", "Karpatská", "Katovná", "Klenová",
    "Kláry Jarunkovej", "Kollárova", "Komenského", "Komín - Ferrata B", "Komínárska - Ferrata ,C",
    "Korundová", "Kostiviarska cesta", "Kostolná", "Kovačická", "Kremeňová",
    "Kremnička", "Kriedovnica", "Krivánska", "Králická cesta", "Krátka",
    "Kráľovohoľská", "Krížna", "Kukučínova", "Kvetinová", "Kyjevské námestie",
    "Kynceľovská cesta", "Ladislava Hudeca", "Lariská", "Laskomerská", "Lazovná",
    "Lesná", "Letná", "Liesková", "Limbová", "Lipová",
    "Lúčičky", "Magurská", "Majerská cesta", "Malachitová", "Malachovská cesta",
    "Marka Čulena", "Martina Hattalu", "Martina Rázusa", "Martinová", "Mateja Bela",
    "Medená", "Medený Hámor", "Michala Miloslava Hodžu", "Mieru", "Mikuláša Kováča",
    "Mičinská cesta", "Mladých budovateľov", "Mlynská", "Mládežnícka", "Mosadzná",
    "Moskovská", "Murgašova", "Muškátová", "Na Dolinky", "Na Graniari",
    "Na Hrbe", "Na Karlove", "Na Kútinách", "Na Lovisku", "Na Lúčkach",
    "Na Motyčinách", "Na Skalici", "Na Starej tehelni", "Na Troskách", "Na Tále",
    "Na Uhlisku", "Na Zábave", "Na plaváreň", "Na úbočí", "Na Čiertolí",
    "Nad plážou", "Nezábudková", "Nešporova", "Nová", "Nové Kalište",
    "Nový Svet", "Námestie Ludvíka Svobodu", "Námestie SNP", "Námestie slobody", "Námestie Ľ. Štúra",
    "Námestie Štefana Moyzesa", "Národná", "Oblačná", "Odbojárov", "Okružná",
    "Opálová", "Orenburská", "Ortútska cesta", "Oty Plávkovej", "Ovocná",
    "Ovčiarska", "Partizánska cesta", "Paľa Bielika", "Pestovateľská", "Petelenova",
    "Petra Karvaša", "Pieninská", "Platinová", "Plánková", "Pod Banošom",
    "Pod Dúbravou", "Pod Flosom", "Pod Hôrkou", "Pod Jesenským vŕškom", "Pod Kalváriou",
    "Pod Skalkou", "Pod Stráňou", "Pod Suchým vrchom", "Pod Turíčkou", "Pod Urpínom",
    "Pod cintorínom", "Pod rybou", "Pod vysielačom", "Podbeľová", "Podháj",
    "Podjavorinskej", "Podlavická cesta", "Ponická", "Povstalecká cesta", "Poľná",
    "Poľovnícka", "Priehon", "Priehrada", "Priemyselná", "Profesora Sáru",
    "Prvosienková", "Pršianska cesta", "Pyritová", "Pánska", "RC dráha",
    "Radvanská", "Rakytovská cesta", "Riečan dolina", "Robotnícka", "Rubínová",
    "Rudelinova", "Rudlovská cesta", "Rudohorská", "Rumelková", "Rutilová",
    "Ruttkaya Nedeckého", "Ružová", "Sadová", "Senická cesta", "Severná",
    "Sitnianska", "Skubínska cesta", "Skuteckého", "Slnečná", "Slnečné stráne",
    "Sládkovičova", "Smaragdová", "Smreková", "Snežná", "Sokolovská",
    "Spojová", "Starohorská", "Stavebná", "Stoličková", "Stredná",
    "Strieborné námestie", "Strmá", "Stromová", "Stránska", "Strážovská",
    "Stupy", "Surovská", "Sásovská cesta", "Tajovského", "Tarnobrežská",
    "Tatranská", "Technická", "Terézie Vansovej", "Tibetský most", "Tibora Andrašovana",
    "Tichá", "Timravy", "Topoľová", "Topásová", "Trieda Hradca Králové",
    "Trieda SNP", "Trnková", "Trubačova veža - Ferrata B", "Tujová", "Tulská",
    "Tyrkysová", "Ulička", "Uľanská cesta", "Vajanského námestie", "Veterná",
    "Viestova", "Višňová", "Vršacká", "Výzva - Ferrata E", "Vŕbová",
    "Wolkerova", "Zadarská", "Zafírová", "Zdenka Mikulu", "Zelená",
    "Zimná", "Zlatá", "Zostupovka - Ferrata", "Zvolenská cesta", "Zvončeková",
    "Záhradná", "Záhumnie", "Závoz", "Čerešňová", "Československej armády",
    "Ďumbierska", "Ľuda Ondrejova", "Ľupčianska", "Šalgotarjánska", "Šalkovská cesta",
    "Šemšelová", "Šimona Jurovského", "Školská", "Šoltésovej", "Štadlerovo nábrežie",
    "Štefánikovo nábrežie", "Švermova", "Šípková", "Železničiarska", "Železná",
    "Žltý piesok",
  ],
  "Bratislava": [
    "1. alej", "1. mája", "2. alej", "29. augusta", "3. alej",
    "4. alej", "5. alej", "7. alej", "8. alej", "8. mája",
    "A. Gwerkovej", "Achátová", "Adámiho", "Agátová", "Akad. mal. Jozefa Nagya",
    "Akvamarínová", "Aladára Radnótiho", "Albertova lávka", "Albrechtova", "Albánska",
    "Albína Brunovského", "Alejová", "Alešova", "Alibernetová", "Alstrova",
    "Alviano", "Alžbetínska", "Am Bahndamm", "Amarelková", "Ambroseho",
    "Ambrova", "Ambrušova", "Americká", "Americké námestie", "Ametystová",
    "Amurská", "Andreja Hadíka", "Andreja Mráza", "Andreja Plávku", "Andrusovova",
    "Anenská", "Antická", "Antolská", "Antona Durvaya", "Antona Floreka",
    "Antona Moyša", "Anízová", "Aragonitová", "Arménska", "Art passage",
    "Astronomická", "Astrová", "Attidova", "Augustína Murína", "Auréliova",
    "Avarská", "Azalková", "Azovská", "Azúrová", "Babuškova",
    "Bachova", "Bagarova", "Bajkalská", "Bajzova", "Bakošova",
    "Balkánska", "Baltská", "Bancíkovej", "Baničova", "Banskobystrická",
    "Banícka", "Baníkova", "Banšelova", "Barancová", "Bardejovská",
    "Bartoňova", "Bartoškova", "Bartókova", "Barónka", "Batkova",
    "Bazalková", "Bazovského", "Bazová", "Baštová", "Bažantia",
    "Bažantnicová", "Beblavého", "Bebravská", "Beckovská", "Bedľová",
    "Begóniová", "Belehradská", "Belianska", "Belicová", "Belinského",
    "Bellova", "Belopotockého", "Belániková", "Bencúrova", "Benediktiho",
    "Beniakova", "Bernolákova", "Beskydská", "Betliarska", "Bezekova",
    "Bezručova", "Beňadická", "Beňovského", "Biela", "Bielkova",
    "Bieloruská", "Bilíkova", "Biskupická", "Björnsonova", "Blagoevova",
    "Blatnická", "Blatúchová", "Bleduľová", "Blumental pasáž", "Blumentálska",
    "Blyskáčová", "Bobuľová", "Bociania", "Bodliaková", "Bodrocká",
    "Bodvianska", "Bohrova", "Bohúňova", "Bojnická", "Borekova",
    "Borievková", "Borinská", "Borisa Nemcova", "Borodáčova", "Borovicová",
    "Borská", "Borágová", "Boskovičova", "Bosákova", "Botanická",
    "Bottova", "Bočná", "Bošániho", "Boženy Němcovej", "Bradlianska",
    "Bradáčova", "Brančská", "Bratislavská", "Bratislavská pasáž", "Bratská",
    "Brestová", "Brezovská", "Brezová", "Brečtanová", "Brežná",
    "Bridlicová", "Brigádnická", "Brižitská", "Brnianska", "Brodná",
    "Brodská", "Bronzová", "Broskyňová", "Brumovická", "Brusnicová",
    "Bršlenová", "Budatínska", "Budovateľská", "Budyšínska", "Bujnákova",
    "Bukovinská", "Buková", "Bukureštská", "Bulharská", "Bullova",
    "Bulíkova", "Burgundská", "Buzalkova", "Bučinová", "Bylinková",
    "Bystrická", "Bystrické sady", "Bystrého", "Bzovícka", "Bárdošova",
    "Béžová", "Bôrik", "Búdková", "Břeclavská", "Cabanova",
    "Cablkova", "Caplárova Past", "Central passage", "Centrálna hviezdica", "Cesta mládeže",
    "Cesta na Gajc", "Cesta na Kamzík", "Cesta na Klanec", "Cesta na Kopáč", "Cesta na Senec",
    "Cesta na Červený most", "Cesta pri Biskupickom ramene", "Cezmínová", "Chalcedónová", "Chalupkova",
    "Charkovská", "Chatová osada", "Chemická", "Chladná", "Chlumeckého",
    "Chodník Eduarda Gregora", "Chorvátska", "Chotárna", "Chrasťová", "Chrenová",
    "Chrobákova", "Chvojnícka", "Cikkerova", "Cintorínska", "Cintulova",
    "Ciroková", "Citrínová", "City Gate Passage", "Colnícka", "Csenárova",
    "Cukrová", "Cyprichova", "Cyrilova", "Cádrova", "Cédrová",
    "Cígeľská", "Daliborovo námestie", "Damborského", "Dankovského", "Danky Košanovej",
    "Dargovská", "Daxnerovo námestie", "Delená", "Delená cesta", "Demänovská",
    "Depo Krasňany", "Desiata", "Detvianska", "Deviata", "Devätinová",
    "Devínska cesta", "Diamantová", "Dlhá", "Dlhá siaha", "Dlhé diely I",
    "Dlhé diely II", "Dlhé diely III", "Dneperská", "Dobrienková", "Dobrovičova",
    "Dobrovského", "Dobšinského", "Dohnalova", "Dohnányho", "Doležalova",
    "Dolichénska", "Dolnokorunská", "Dolnozemská cesta", "Dolná", "Domašská",
    "Domiciánova", "Dominika Tatarku", "Domkárska", "Domové role", "Donnerova",
    "Donovalova", "Donská", "Dopravná", "Dorastenecká", "Dostojevského rad",
    "Dr. Vladimíra Clementisa", "Dražická", "Drevená", "Drieňová", "Driver 8",
    "Drobného", "Dropia", "Drotárska cesta", "Drozdová", "Druhá",
    "Druidská", "Družicová", "Družobná", "Družstevná", "Dubnická",
    "Dubová", "Dubáková", "Dudova", "Dudvážska", "Dulovo námestie",
    "Dunajská", "Dvanásta", "Dvojkrížna", "Dvor 66", "Dvořákovo nábrežie",
    "Dúbravská cesta", "Dúbravčická", "Edisonova", "Eduarda Wenzla", "Egrešová",
    "Einsteinova", "Eisnerova", "Elektrárenská", "Estónska", "Exnárova",
    "F. Kostku", "Fadruszova", "Fajnorovo nábrežie", "Farebná", "Farmárska",
    "Farská", "Farského", "Fazuľová", "Fedinova", "Fedákova",
    "Ferienčíkova", "Fialkové údolie", "Fialová", "Fibichova", "Figová",
    "Fikusová", "Filiálne nádražie", "Firmova", "Fiľakovská", "Floriánska",
    "Floriánske námestie", "Fláviovska", "Fláviovská", "Flöglova", "Fongová",
    "Francisciho", "Francúzskych partizánov", "Frankovská", "Františka Kubu", "Františka Oswalda",
    "Františka Schmuckera", "Františkánska", "Františkánske námestie", "Fraňa Kráľa", "Furdekova",
    "Furmanská", "Furmintská", "Fándlyho", "Gabčíkova", "Gagarinova",
    "Gajarská", "Gajc", "Gajova", "Galaktická", "Galandova",
    "Galbavého", "Gallayova", "Gallova", "Galská", "Galvaniho",
    "Garáž Opera", "Gavlovičova", "Gašparíkova", "Gaštanová", "Gbelská",
    "Gelnická", "Gemerská", "Gen. mjr. Antona Petráka", "Generála Goliana", "Generála Viesta",
    "Geologická", "Gercenova", "Gerulatská", "Gessayova", "Gettingova",
    "Godrova", "Gogoľova", "Goláňova", "Gondova", "Goralská",
    "Gorazdova", "Gorkého", "Grand Bazár", "Granitová", "Granátová",
    "Gregorovej", "Gronárska", "Grubičova", "Gruzínska", "Gránerova",
    "Grösslingová", "Gunduličova", "Guothova", "Gusevova", "Gustáva Mallého",
    "Haanova", "Haburská", "Habánska", "Hadia cesta", "Hadincová",
    "Hadriánova", "Hagarova", "Halašova", "Halštatská", "Hamuliakova",
    "Handlovská", "Hanulova", "Hany Meličkovej", "Hany Ponickej", "Hanácka",
    "Hargašova", "Harmanecká", "Harmincova", "Hasičská", "Hattalova",
    "Havelkova", "Havlíčkova", "Havrania", "Haydnova", "Herlianska",
    "Heydukova", "Heyrovského", "Hečkova", "Hlavatého", "Hlavná",
    "Hlavné námestie", "Hlaváčikova", "Hlbinná", "Hlboká cesta", "Hlinícka",
    "Hlivová", "Hlohová", "Hlučínska", "Hnilecká", "Hodonínska",
    "Hodálova", "Hodžovo námestie", "Holekova", "Hollého", "Holubyho",
    "Holíčska", "Homolova", "Hontianska", "Horcová", "Horná",
    "Horná Vančurova", "Hornádska", "Horné Židiny", "Horská", "Horárska",
    "Hospodárska", "Hrabovinská", "Hrabový chodník", "Hrachová", "Hradištná",
    "Hradná", "Hradné údolie", "Hradská", "Hraničiarska", "Hraničná",
    "Hrdličkova", "Hrebendova", "Hriňovská", "Hroboňova", "Hrobákova",
    "Hrobárska", "Hronská", "Hroznová", "Hrušková", "Hruškový sad",
    "Hrušovská", "Hríbová", "Hrôzostrašný chodníček", "Hubeného", "Hudecova",
    "Humenské námestie", "Hummelova", "Hurbanovo námestie", "Husova", "Hutnícka",
    "Hviezdna", "Hviezdoslavova", "Hviezdoslavovo námestie", "Hyacintová", "Hybešova",
    "Hydinárska", "Hájnická", "Hájová", "Hájovňa", "Hálkova",
    "Hálova", "Húščavova", "Hýlia", "Hýrošova", "Iberková",
    "Ibišteková", "Ihličnatá", "Ihrisková", "Ilkovičova", "Ilýrska",
    "Imelová", "Imricha Karvaša", "Inovecká", "Ipelská", "Ipeľská",
    "Irisová", "Irkutská", "Iršajská", "Iskerníková", "Istrijská",
    "Ivana Bukovčana", "Ivana Horvátha", "Ivana Kadlečíka", "Ivanská cesta", "Iľjušinova",
    "J. Valašťana Dolinského", "Jabloňová", "Jabloňový sad", "Jadranská", "Jadrová",
    "Jahodová", "Jakabova", "Jakubovo námestie", "Jakubská", "Jakubíkova",
    "Jalovcová", "Jamnického", "Janka Alexyho", "Janka Kráľa", "Jankolova",
    "Jankovičova", "Janotova", "Janoškova", "Jantárová", "Jantárová cesta",
    "Janáčkova", "Janíkovské role", "Jančova", "Janšákova", "Jarabinková",
    "Jarná", "Jaroslavova", "Jarovce", "Jarošova", "Jasencová",
    "Jaseňová", "Jaskový rad", "Jasná", "Jasovská", "Jaspisová",
    "Jastrabia", "Jastrabinová", "Javorinská", "Javorová", "Jazdecká",
    "Jazerná", "Jazmínová", "Jačmenná", "Jašíkova", "Jedenásta",
    "Jedlíkova", "Jedľová", "Jegenešská", "Jelačičova", "Jelenia",
    "Jelšová", "Jesenná", "Jesenského", "Jesienková", "Jeséniova",
    "Jiráskova", "Jiskrova", "Jonatánová", "Josepha Poppera", "Jozefa Cígera Hronského",
    "Jozefa Kronera", "Jozefa Mikisitsa", "Jozefa Vachovského", "Jozefská", "Jungmannova",
    "Junácka", "Jura Hronca", "Jurigovo námestie", "Jurkovičova", "Jurovského",
    "Jurská", "Justičná", "Jána Dekana", "Jána Holíka", "Jána Jonáša",
    "Jána Lajčiaka", "Jána Langoša", "Jána Poničana", "Jána Raka", "Jána Smreka",
    "Jána Stanislava", "Jánošíkova", "Jégého", "Jókaiho", "Júlová",
    "Júnová", "K Horanskej studni", "K Horánskej studni", "K lomu", "K pasienkom",
    "K zlatému rohu", "K Železnej studienke", "Kadnárova", "Kafendova", "Kajerka",
    "Kalinová", "Kalinčiakova", "Kalištná", "Kamenistá", "Kamenná",
    "Kamenné námestie", "Kamenný most v bažantnici", "Kamenárska", "Kameňolom", "Kameňák",
    "Kamilková", "Kamzík-les", "Kamzíkov vrch", "Kaméliová", "Kananefatská",
    "Kapicova", "Kapitulská", "Kaplinská", "Kapsičková", "Kapsohradská",
    "Kapucínska", "Kapušianska", "Karadžičova", "Karloveská", "Karloveské rameno",
    "Karola Adlera", "Karpatská", "Karpatské námestie", "Kataríny Brúderovej", "Kaukazská",
    "Kavyľová", "Kazanská", "Kačínska dolina", "Kašmírska", "Kaštieľska",
    "Keltská", "Kempelenova", "Ketelec", "Kežmarské námestie", "Kladnianska",
    "Klariská", "Klatovská", "Klemensova", "Klenová", "Klimkovičova",
    "Klincová", "Klobučnícka", "Klokočova", "Kláštorská", "Kmeťovo námestie",
    "Knižkova dolina", "Koceľova", "Kohútova", "Kollerova", "Kollárova",
    "Kollárovo námestie", "Kolmá", "Kolárska", "Kolískova", "Komenského námestie",
    "Kominárska", "Komonicová", "Komárnická", "Komárovská", "Komárňanská",
    "Koncová", "Koniarkova", "Konopiská", "Konopná", "Konvalinková",
    "Konventná", "Kopanice", "Kopaničarska", "Koperníkova", "Koprivnická",
    "Kopčianska", "Korabinského", "Koreničova", "Koreňová", "Korunská",
    "Korytnická", "Korálová", "Kosatcová", "Kosodrevinová", "Kostlivého",
    "Kostolná", "Kovorobotnícka", "Kovová", "Kovácsova", "Kováčska",
    "Kozia", "Koziarka", "Kozičova", "Kozmonautická", "Kočánkova",
    "Koľajná", "Košická", "Kožušnícka", "Kpt. Jána Rašu", "Krahulčia",
    "Krajinská", "Krajinská cesta", "Krajná", "Krakovská", "Krasinského",
    "Kraskova", "Krasovského", "Krasňanská", "Kratiny", "Kremencová",
    "Kremeľská", "Kremnická", "Kresánkova", "Kristy Bendovej", "Krivá",
    "Krivé Jarky Trail", "Krištáľová", "Križkova", "Križovatka Jozefa Čabelku", "Krmanova",
    "Krokusová", "Krompašská", "Krupinská", "Krupkova", "Krušpánová",
    "Krásna", "Krásnohorská", "Krátka", "Kráľovské údolie", "Kríková",
    "Krížna", "Krčméryho", "Kubačova", "Kubániho", "Kubínska",
    "Kudlákova", "Kuklovská", "Kukuričná", "Kukučínova", "Kultúrna",
    "Kulíškova", "Kuneradská", "Kunovská", "Kupeckého", "Kurucova",
    "Kutlíkova", "Kutuzovova", "Kuzmányho", "Kučovanická", "Kvačalova",
    "Kvetinárska", "Kvetná", "Kyjevská", "Kysucká", "Kôstková",
    "Kúkoľová", "Kúpeľná", "Kútska", "Kýčerského", "Kĺzavá",
    "Kľukatá", "Laborecká", "Labutia", "Lachova", "Lackova",
    "Ladislava Batthyányho", "Ladislava Dérera", "Ladislava Sáru", "Ladislava Šefca", "Ladzianskeho",
    "Lamanského", "Lamač", "Lamačská cesta", "Landauova", "Landererova",
    "Langsfeldova", "Lančárska", "Laskomerského", "Latorická", "Laténska",
    "Laurinská", "Laurotová", "Laury Henckelovej", "Laučekova", "Lazaretská",
    "Lediny", "Legerského", "Legionárska", "Lehockého", "Leknová",
    "Lenardova", "Leopolda Jablonku", "Leopoldov majer", "Lermontovova", "Lesná",
    "Lesnícka", "Letecká", "Letná", "Levanduľová", "Levická",
    "Levočská", "Levárska", "Leánska", "Leškova", "Lichardova",
    "Lidická", "Lieskovec", "Lieskovská cesta", "Lietavská", "Liga pasáž",
    "Ligurčeková", "Likavská", "Limbová", "Linzbothova", "Lipkavcová",
    "Lipnicová", "Lipovinová", "Lipová", "Lipského", "Liptovská",
    "Lisovňa", "Listová", "Litovská", "Lodná", "Lombardiniho",
    "Lomnická", "Lomonosovova", "Longobardská", "Lopenícka", "Lopárska",
    "Lopúchová", "Lotyšská", "Lovinského", "Lozornianska", "Lubinská",
    "Luhačovická", "Lužická", "Lužná", "Lykovcová", "Lysákova",
    "Líščie nivy", "Líščie údolie", "Lónyaiová", "Lúčna", "Lýcejná",
    "M. Curie Sklodowskej", "M. Schneidra Trnavského", "Macharova", "Madáchova", "Magnetová",
    "Magnezitová", "Magnóliová", "Magurská", "Majakovského", "Majerníkova",
    "Majerská", "Majoránová", "Makovického", "Maková", "Malachitová",
    "Malagová", "Malinová", "Malodunajská", "Malokarpatské námestie", "Malokrasňanská",
    "Malá", "Malé Pálenisko I", "Malé Pálenisko III", "Malé Pálenisko IV", "Malý trh",
    "Mamateyova", "Mandľovníková", "Mandľová", "Manina", "Marchfeld Schnellstraße",
    "Margarétová", "Marhuľová", "Mariána Kochanského", "Mariánska", "Markova",
    "Martina Granca", "Martinengova", "Martinská", "Martinčekova", "Martákovej",
    "Maríny Paulínyovej", "Maróthyho", "Mateja Bela", "Mateja Encingera", "Matejkova",
    "Matičná", "Matúškova", "Matúšova", "Maximiliána Hella", "Maďarská",
    "Medená", "Medovková", "Medová", "Medveďovej", "Medzierka",
    "Medzilaborecká", "Merlotová", "Mesačná", "Mestská", "Meteorová",
    "Metodova", "Mečíková", "Michala Bučiča", "Michala Greguša", "Michalská",
    "Michalský chodník", "Mickiewiczova", "Mierová", "Mikovíniho", "Mikulášska",
    "Milana Kolibiara", "Milana Marečka", "Milana Pišúta", "Milana Šimečku", "Miletičova",
    "Mišíkova", "Mliekárenská", "Mlynarovičova", "Mlynská", "Mlynská dolina",
    "Mlynské luhy", "Mlynské nivy", "Mlyny", "Mládežnícka", "Modranská",
    "Modricová", "Modrý chodník", "Mojmírova", "Mokrohájska cesta", "Mokráň záhon",
    "Moldavská", "Molecova", "Monardová", "Moravská", "Morušová",
    "Moskovská", "Most Apollo", "Most Lanfranconi", "Most SNP", "Mostná",
    "Mostová", "Motýlia", "Moyzesova", "Moyšova", "Mozartova",
    "Mošovského", "Mramorová", "Mraziarenská", "Mrázová", "Muchovo námestie",
    "Mudrochova", "Mudroňova", "Murgašova", "Muránska", "Murárska",
    "Muškátová", "Muštová", "Myjavská", "Máchova", "Májkova",
    "Májová", "Málová", "Mánesovo námestie", "Mínešská", "Múzejná",
    "Mýtna", "Na Ahoji", "Na Baránku", "Na Brezinách", "Na Briežkoch",
    "Na Grbe", "Na Grunte", "Na Hliníku", "Na Holom vrchu", "Na Hrebienku",
    "Na Kalvárii", "Na Kampárke", "Na Koziarke", "Na Krčoch", "Na Pažiti",
    "Na Revíne", "Na Riviére", "Na Roličkách", "Na Sitine", "Na Slanci",
    "Na Slavíne", "Na Vlkovkách", "Na Vtáčniku", "Na Zlatej nohe", "Na barine",
    "Na doline", "Na hriadkach", "Na hrádzi", "Na jarku", "Na kaštieli",
    "Na kopci", "Na križovatkách", "Na lánoch", "Na medzi", "Na mýte",
    "Na pasekách", "Na paši", "Na piesku", "Na pántoch", "Na rozhliadke",
    "Na skale", "Na spojke", "Na stráni", "Na sútoku", "Na varte",
    "Na vrátkach", "Na vyhliadke", "Na výslní", "Na vŕšku", "Na úvrati",
    "Na Štyridsiatku", "Nad Dunajom", "Nad Gronárom", "Nad Sihoťou", "Nad Válkom",
    "Nad jazierkom", "Nad kúriou", "Nad lomom", "Nad lúčkami", "Nad ostrovom",
    "Nad záhradami", "Narcisová", "Nechtíková", "Nedbalova", "Nefritová",
    "Nejedlého", "Nekrasovova", "Nemecká dolina", "Nemčíkova", "Neronetová",
    "Nerudova", "Nevská", "Nevädzová", "Nezvalova", "Nezábudková",
    "Nitrianska", "Niťová", "Nobelova", "Nobelovo námestie", "Novackého",
    "Novinárska", "Novobanská", "Novodvorská", "Novohorská", "Novohradská",
    "Novosadná", "Novosvetská", "Novoveská", "Nová", "Nová Bellova",
    "Nová Koziarka", "Nová Manina", "Nová Rožňavská", "Nové Pálenisko", "Nové záhrady I",
    "Nové záhrady II", "Nové záhrady III", "Nové záhrady IV", "Nové záhrady V", "Nové záhrady VI",
    "Nové záhrady VII", "Nové Šuty", "Nový záhon", "Nábrežie Milana Rastislava Štefánika", "Nábrežie arm. gen. Ludvíka Svobodu",
    "Nábrežie armádneho generála Ľudvíka Slobodu", "Nábrežie Ľubomíra Kadnára", "Nábrežná", "Nábělkova", "Nádvorie Starej radnice",
    "Nákovná", "Nákupná", "Námestie 1. mája", "Námestie 6. apríla", "Námestie Alexandra Dubčeka",
    "Námestie Andreja Hlinku", "Námestie Biely kríž", "Námestie Eugena Suchoňa", "Námestie F. X. Messerschmidta", "Námestie Franza Liszta",
    "Námestie Jána Kostru", "Námestie Jána Pavla II.", "Námestie Martina Benku", "Námestie Mateja Korvína", "Námestie Nežnej revolúcie",
    "Námestie SNP", "Námestie generála Viesta", "Námestie hraničiarov", "Námestie rodiny", "Námestie slobody",
    "Námestie sv. Floriána", "Námestie sv. Petra a Pavla", "Námestie Ľudovíta Štúra", "Nížinná", "Obchodná",
    "Obežná", "Obilná", "Oblačná", "Oblúková", "Ochotnícka",
    "Odbojárov", "Odborárska", "Odborárske námestie", "Odeská", "Oeserov rad",
    "Okrajovka", "Okružná", "Okánikova", "Olbrachtova", "Oleandrová",
    "Olejkárska", "Olivová", "Ollarekova", "Olympijské námestie", "Olšová",
    "Ondavská", "Ondreja Štefanka", "Ondrejovova", "Ondrejská", "Opavská",
    "Opletalova", "Opálová", "Oranžová", "Oravská", "Orchideová",
    "Orechová", "Orechová cesta", "Orechový rad", "Orenburská", "Orešianková",
    "Orgovánová", "Oriešková", "Orlíčková", "Ormisova", "Oráčska",
    "Osadná", "Osijecká", "Osiková", "Oskorušová", "Osloboditeľská",
    "Ostravská", "Ostredková", "Ostricová", "Ostriežová", "Ostružinová",
    "Osuského", "Osvetová", "Ota Holúska", "Otonelská", "Ovocná",
    "Ovručská", "Ovsená", "Ovsištské námestie", "Ovčiarska", "Očovská",
    "Ožvoldíkova", "Padlých hrdinov", "Pajštúnska", "Palackého", "Palinová",
    "Palisády", "Palkovičova", "Palmová", "Palárikova", "Panenská",
    "Pankúchova", "Panská", "Panónska cesta", "Papraďová", "Papánkovo námestie",
    "Parcelná", "Parenicová", "Parková", "Partizánska", "Pasienková",
    "Passage Gorkého", "Passage Old City", "Pastierska", "Pasáž Elektro", "Pasáž Luxor",
    "Pasáž Miletičova", "Pasáž Rybárska brána", "Pasáž Zlatý jeleň", "Paulínyho", "Pave Vukoviča",
    "Pavla Blaha", "Pavla Horova", "Pavlovičova", "Pavlovova", "Pavlovská",
    "Pažického", "Pažítková", "Pekná cesta", "Pekná vyhliadka", "Pekníkova",
    "Perličková", "Perlová", "Pernecká", "Pestovateľská", "Petara Pasicha",
    "Peterská", "Petra Legnera", "Petržalská", "Petržalské korzo", "Petzvalova",
    "Petőfiho", "Pezinská", "Pečnianska", "Pešia zóna", "Piata",
    "Pieskovcová", "Piesková", "Piesočná", "Piešťanská", "Pifflova",
    "Pilárikova", "Pinotová", "Pionierska", "Pivonková", "Plachého",
    "Plamienková", "Planckova", "Planét", "Platanová", "Plavecká",
    "Plickova", "Plitvická", "Plk. Prvoniča", "Pluhová", "Plynárenská",
    "Plzenská", "Plánky", "Plátennícka", "Plávková", "Pobrežná",
    "Pod Bôrikom", "Pod Glavicou", "Pod Klepáčom", "Pod Kobylou", "Pod Krásnou hôrkou",
    "Pod Lipovým", "Pod Mníšskou horou", "Pod Rakytami", "Pod Rovnicami", "Pod Strážami",
    "Pod Vachmajstrom", "Pod Vajspetrom", "Pod Vtáčnikom", "Pod Válkom", "Pod Zemným vrchom",
    "Pod Zečákom", "Pod agátmi", "Pod brehmi", "Pod gaštanmi", "Pod kopčekmi",
    "Pod krížom", "Pod lesom", "Pod lipami", "Pod násypom", "Pod skalou",
    "Pod vinicami", "Pod záhradami", "Podbeľová", "Podbrezovská", "Podchod pamäti",
    "Podchod študentov 16. novembra 1989", "Podhorská", "Podhorského chodník", "Podháj", "Podjavorinskej",
    "Podjazd", "Podkarpatská", "Podkerepušky", "Podkolibská", "Podkorunská",
    "Podlesná", "Podlučinského", "Podniková", "Podpriehradná", "Podtatranského",
    "Podunajská", "Podzáhradná", "Pohraničiarska signálka", "Pohraničníkov", "Pohronská",
    "Pohánková", "Polereckého", "Polianky", "Poludníková", "Polárna",
    "Poniklecová", "Popolná", "Popovova", "Popradská", "Porubského",
    "Potočná", "Považanova", "Považská", "Povoznícka", "Povraznícka",
    "Poľnohospodárska", "Poľná", "Poľný mlyn", "Poľovnícka", "Poľská",
    "Poštová", "Požiarnická", "Prasličková", "Pračanská", "Prašná",
    "Pražská", "Prepoštská", "Prešernova", "Prešovská", "Pri Bielom Kríži",
    "Pri Bielom kríži", "Pri Dynamitke", "Pri Habánskom mlyne", "Pri Hrubej lúke", "Pri Pastierni",
    "Pri Rusovskom ramene", "Pri Seči", "Pri Starom háji", "Pri Suchom mlyne", "Pri Vápenickom potoku",
    "Pri dvore", "Pri gaštanovej aleji", "Pri hradnej studni", "Pri hrádzi", "Pri kolíske",
    "Pri kríži", "Pri lesostepi", "Pri letisku", "Pri majeri", "Pri mlyne",
    "Pri nadjazde", "Pri parku", "Pri pasienku", "Pri pekárni", "Pri pieskovom hone",
    "Pri potoku", "Pri rybníku", "Pri smaltovni", "Pri starej prachárni", "Pri starom letisku",
    "Pri starom mýte", "Pri strelnici", "Pri struhe", "Pri tehelni", "Pri trati",
    "Pri vinohradoch", "Pri vodnej veži", "Pri vojenskom cintoríne", "Pri zvonici", "Pri Čiernom lese",
    "Pri Šajbách", "Pri šanci", "Pri štadióne", "Pri žrebčíne", "Priama cesta",
    "Pribinova", "Pribinova-zimný prístav", "Pribišova", "Pribylinská", "Pridánky",
    "Priehradná", "Priekopnícka", "Priekopy", "Priemyselná", "Prievozská",
    "Priečna", "Primaciálne námestie", "Prokofievova", "Prokopa Veľkého", "Prokopova",
    "Prosová", "Protinapoleónsky val", "Prvosienková", "Prvá", "Prídavkova",
    "Príjazdná", "Príkopova", "Prímoravská", "Prípojná", "Prístavná",
    "Prístavný most", "Prúdová", "Pustá", "Puškinova", "Pyrenejská",
    "Pálavská", "Pántikova", "Páričkova", "Párna", "Pílová",
    "Píniová", "Pôvabnicová", "Púchovská", "Púpavová", "Pútnická",
    "Pýrová", "Pšeničná", "Radarová", "Radlinského", "Radničná",
    "Radničné námestie", "Radoslava Hošeka", "Radvanská", "Rajecká", "Rajská",
    "Rajtákova", "Rajčianska", "Raketová", "Rakytníková", "Rakúsko-pruské námestie",
    "Rascová", "Rastislavova", "Rastlinná", "Račianska", "Račianske mýto",
    "Ražná", "Rebarborová", "Rebríčková", "Regrútska", "Remeselnícka",
    "Repašského", "Repková", "Repná", "Repíková", "Revolučná",
    "Revúcka", "Rezedová", "Rešetkova", "Riazanská", "Ribayova",
    "Riečna", "Rigeleho", "Riviéra", "Rizlingová", "Riznerova",
    "Robotnícka", "Rohatka", "Romanova", "Rosná", "Rostovská",
    "Rovinka", "Rovniankova", "Rovná", "Rovníková", "Royko pasáž",
    "Royova", "Rozchodníková", "Rozmarínová", "Rozvodná", "Rozálska",
    "Roľnícka", "Rošického", "Rožňavská", "Rubinetová", "Rubinsteinova",
    "Rubínová", "Rudavská", "Rudnayovo námestie", "Rudnícka", "Rudolfa Mocka",
    "Rudroffova", "Rulandská", "Rumančeková", "Rumunská", "Rusovská cesta",
    "Rustaveliho", "Rutová", "Rušňová", "Ruženínová", "Ružinovská",
    "Ružičková", "Ružomberská", "Ružová dolina", "Rybničná", "Rybárska brána",
    "Rytierska", "Rácova", "Rádiová", "Rákosová", "Ráztočná",
    "Rázusovo nábrežie", "Révová", "Ríbezľová", "Rímska", "Röntgenova",
    "Rýdziková", "Rýnska", "Sabinovská", "Sad Janka Kráľa", "Sadmelijská",
    "Sadová", "Samova", "Saratovská", "Sartorisova", "Sasinkova",
    "Satinského", "Savignonská", "Schengenská", "Schillerova", "Schody pri Starej Vodárni",
    "Schody rabína Armína Friedera", "Scilová", "Seberíniho", "Sedlárska", "Sedmokrásková",
    "Segnerova", "Segnáre", "Sekulská", "Sekurisova", "Sekýľska",
    "Semenárska", "Semianova", "Semilonská", "Senická", "Senná",
    "Septimiova", "Severná tangenta", "Severovcov", "Sečovská", "Sibírska",
    "Siedma", "Sienkiewiczova", "Silvánska", "Sinokvetná", "Sitnianska",
    "Skalická cesta", "Skalná", "Skalníková", "Skerličova", "Sklabinská",
    "Skladištná", "Sklenárova", "Sklenárska", "Skorocelová", "Skuteckého",
    "Skýcovská", "Sladová", "Slatinská", "Slavónska", "Slepá",
    "Sliačska", "Sliezska", "Slivková", "Slivkový sad", "Slnečnicová",
    "Slnečná", "Slovanská", "Slovanské nábrežie", "Slovienska", "Slovinec",
    "Slovinská", "Slovnaftská", "Slowackého", "Sládkovičova", "Slávičie údolie",
    "Smaragdová", "Smetanova", "Smikova", "Smolenická", "Smolnícka",
    "Smrečianska", "Smržová", "Snežienková", "Sochorova", "Socháňova",
    "Soferove schody", "Sokolská", "Sokolíkova", "Solivarská", "Sološnická",
    "Solúnska", "Somolického", "Sonntagova", "Sosnová", "Sovia",
    "Spišská", "Spojná", "Spoločenská", "Sputniková", "Spádová",
    "Spätná cesta", "Sreznevského", "Srnčia", "Stachanovská", "Stairs",
    "Stanekova", "Staničná", "Starhradská", "Starohájska", "Staromestská",
    "Staromlynská", "Starorímska", "Staroturský chodník", "Stará Ivanská cesta", "Stará Klenová",
    "Stará Prievozská", "Stará Stupavská", "Stará Vajnorská", "Stará vinárska", "Stará Černicová",
    "Staré Grunty", "Staré ihrisko", "Staré záhrady", "Starý most", "Stavbárska",
    "Staviteľská", "Steinov dvor", "Stepná cesta", "Stodolova", "Stoklasová",
    "Stolárska", "Strakova", "Strapcová", "Stratená", "Stredná",
    "Strelecká", "Strelkova", "Strečnianska", "Strminová", "Strmá cesta",
    "Strmé sady", "Strmý bok", "Strmý vŕšok", "Strojnícka", "Stromová",
    "Stropkovská", "Struková", "Strážna", "Strážnická", "Studenohorská",
    "Studená", "Stupavská", "Stálicová", "Suchohradská", "Suchohríbová",
    "Suchá", "Suché mýto", "Sudová", "Sumbalova", "Sv. Vincenta",
    "Svetlá", "Svidnícka", "Svoradova", "Svornosti", "Svrčia",
    "Svätoplukova", "Svätovavrinecká", "Svätovojtešská", "Svätého Pia X.", "Svätého Urbana",
    "Svébska", "Svíbová", "Syslia", "Szapáryho", "Súbežná",
    "Súhvezdná", "Súkennícka", "Súmračná", "Súľovská", "Súťažná",
    "Sĺňavská", "Tabaková", "Tablicova", "Tajovského", "Talichova",
    "Tallerova", "Tatranská", "Tavaríkova osada", "Tbiliská", "Technická",
    "Tehelná", "Tehelňa", "Tehliarska", "Tekovská", "Telocvičná",
    "Tematínska", "Teplická", "Terchovská", "Teslova", "Tetmayerova",
    "Tešedíkova", "Thurzova", "Tibenského", "Tibériova", "Tichá",
    "Tilgnerova", "Timravina", "Tobrucká", "Tokajícka", "Tolstého",
    "Tomanova", "Tomislava P. Kolakoviča", "Tománkova", "Tomášikova", "Toplianska",
    "Topoľová", "Topoľčianska", "Topásová", "Toryská", "Továrenská",
    "Trajánova", "Tramínová", "Tranovského", "Trebišovská", "Trebuľková",
    "Trenčianska", "Treskoňova", "Tretia", "Trhová", "Trinásta",
    "Trnavská cesta", "Trnavské mýto", "Trnková", "Trojdomy", "Trojičné námestie",
    "Trstínska", "Trávna", "Tuhovská", "Tulipánová", "Tunel Karpaty",
    "Tunel Sitina", "Tupolevova", "Tupého", "Turbínová", "Turistická",
    "Turnianska", "Turčianska", "Tučkova", "Tvarožkova", "Tylova",
    "Tymiánová", "Tyrkysová", "Tyršovo nábrežie", "Táborská", "Tŕňová",
    "Uhliská", "Uhorková", "Uhrova", "Uhrovecká", "Ukrajinská",
    "Urbánkova", "Urbárska", "Urpínska", "Ursínyho", "Uránová",
    "Uršulínska", "Uzbecká", "Učiteľská", "Ušiakova", "V záhradách",
    "Vajanského nábrežie", "Vajnorská", "Valachovej", "Valašská", "Valchárska",
    "Valentiniánova", "Valentína Matrku", "Vansovej", "Vančurova", "Varínska",
    "Varšavská", "Vavilovova", "Vavrinecká", "Vavrínová", "Vazovova",
    "Velehradská", "Veltlínska", "Vendelínska", "Ventúrska", "Veternicová",
    "Veterná", "Vetvová", "Vetvárska", "Veľké Štepnice", "Vidlicová",
    "Viedenská cesta", "Vietnamská", "Vihorlatská", "Viktora Tegelhoffa", "Viktorínova",
    "Vilová", "Vincenta Hložníka", "Viniferová", "Viničná", "Vinohradnícka",
    "Vislianska", "Višňová", "Vladimíra Jukla", "Vlastenecké námestie", "Vlašská",
    "Vlárska", "Vlčie hrdlo", "Vlčkova", "Vojtecha Ondroucha", "Vosková",
    "Votrubova", "Vrakunská", "Vrakunská cesta", "Vrakunská promenáda", "Vranovská",
    "Vrančovičova", "Vratičová", "Vrbenského", "Vrbánska", "Vrchná",
    "Vresová", "Vretenová", "Vrábeľská", "Vrátňanská", "Vrútocká",
    "Vtáčie údolie", "Vtáčiková cesta", "Vukovarská", "Vyhliadka", "Vyhnianska cesta",
    "Vysokohorská", "Vysoká", "Vyšehradská", "Vyšná", "Vápencová",
    "Vápenka", "Vápenná", "Vážska", "Vígľašská", "Vínna",
    "Víťazná", "Východná", "Výhonská", "Výria", "Výtvarná",
    "Vývojová", "Včeláriková", "Včelárska", "Vŕbová", "Wattova",
    "Wilsonova", "Wolkrova", "Za bránou", "Za farou", "Za humnami",
    "Za kasárňou", "Za mlynom", "Za sokolovňou", "Za stanicou", "Za tehelňou",
    "Zadarská", "Zadunajská cesta", "Zafírová", "Zamatová", "Zavadilova",
    "Zbrody", "Zdenky Schelingovej", "Zdravotnícka", "Zeleninová", "Zelenohorská",
    "Zelená", "Zelené terasy", "Zelinárska", "Zelnická", "Zhorínska",
    "Zichyho", "Zidiny", "Zimná", "Zlatohorská", "Zlatohríbová",
    "Zlatá", "Zlaté piesky", "Zlaté schody", "Znievska", "Zobová",
    "Zochova", "Zohorská", "Zrínskeho", "Zuzany Chalupovej", "Zvolenská",
    "Zvončeková", "Záborského", "Záhorská", "Záhorácka", "Záhradkárska",
    "Záhradná", "Záhradnícka", "Záhrady", "Záhrebská", "Záhumenná",
    "Záhumenská", "Zákutie", "Zálužická", "Zámocká", "Zámocké schody",
    "Zámočnícka", "Západná", "Západný rad", "Záporožská", "Zárubová",
    "Záruby", "Zátišie", "Zátureckého", "Závadská", "Záveterná",
    "Závodná", "Závodníkova", "Závodu Matador", "k internátu", "Ágosta Sőtéra",
    "Ílová", "Ónyxová", "Ôsma", "Údernícka", "Údolná",
    "Úprkova", "Úradnícka", "Úvozná", "Úzka", "Úžiny",
    "Čachtická", "Čajakova", "Čajkovského", "Čakanková", "Čaklovská",
    "Čalovská", "Čapkova", "Čavojského", "Čelakovského", "Čerencová",
    "Čerešňová", "Čerešňový sad", "Černicová", "Černockého", "Černyševského",
    "Červená", "Červeňova", "Červeňákova", "Československých parašutistov", "Československých tankistov",
    "Česká", "Čečinová", "Čiernohorská", "Čiernovodská", "Čierny chodník",
    "Čiližská", "Čipkárska", "Čmelíkova", "Čmeľovec", "Čremchová",
    "Čulenova", "Čučoriedková", "Čárskeho", "Ďatelinová", "Ďumbierska",
    "Ďurgalova", "Ľadová", "Ľaliová", "Ľanová", "Ľubietovská",
    "Ľubochnianska", "Ľubovnianska", "Ľubovníková", "Ľubľanská", "Ľuda Zúbka",
    "Ľudmily Kraskovskej", "Ľudové námestie", "Ľudovíta Fullu", "Šachorová", "Šafranová",
    "Šafárikovo námestie", "Šagátová", "Šaldova", "Šalviová", "Šamorínska",
    "Šancová", "Šarišská", "Šaštínska", "Ševčenkova", "Šiesta",
    "Šikmá", "Šinkovské", "Šintavská", "Široká", "Škarniclova",
    "Školská", "Škovránčia", "Škultétyho", "Šoltésovej", "Špaldová",
    "Špieszova", "Špitálska", "Športová", "Štedrá", "Štefana Králika",
    "Štefana Majera", "Štefana Rosívala", "Štefanovičova", "Štefunkova", "Štefánikova",
    "Štepná", "Štetinova", "Štiavnická", "Štrbská", "Štvrtá",
    "Štyndlova", "Štítová", "Štúrova", "Šulekova", "Šumavská",
    "Šustekova", "Šutráková", "Šuty", "Šuňavcova", "Švabinského",
    "Švajčiareň", "Švantnerova", "Šándorova", "Šándorove schody", "Šášovská",
    "Šípková", "Šípová", "Šíravská", "Šúrska", "Šťastná",
    "Žabotova", "Žarnovická", "Žatevná", "Žehrianska", "Železničiarska",
    "Železničná", "Železná", "Želiarska", "Žellova", "Žiacka",
    "Žiarska", "Židovská", "Žihľavová", "Žilinská", "Žitavská",
    "Žitná", "Žitvayova", "Živnostenská", "Žižkova", "Žltá",
    "Žulová", "Župné Námestie",
  ],
  "Košice": [
    "1", "1. mája", "10", "11", "12",
    "13", "14", "15", "16", "17",
    "18", "19", "2", "20", "21",
    "22", "23", "24", "25", "26",
    "27", "28", "29", "3", "30",
    "31", "32", "33", "34", "35",
    "36", "37", "4", "5", "6",
    "7", "8", "9", "Abovská", "Adamova",
    "Adlerova", "Agátová", "Alejová", "Alejová, gymnázium", "Alexandra Dubčeka",
    "Alešovo nábrežie", "Alvinczyho", "Alšavská", "Alžbetina", "Americká trieda",
    "Amfiteáter", "Amurská", "Andraščíkova", "Andreja Kvasa", "Aničkin park",
    "Astória", "Atletická", "Aténska", "Austrálska trieda", "Azovská",
    "BUS", "Bahýľova", "Bajzova", "Baltická", "Baničova",
    "Bankov", "Banícka", "Barca", "Barca, kultúrny dom", "Bardejovská",
    "Barčianska", "Bauerova", "Bazalková", "Bazová", "Bačíkova",
    "Baštová", "Bašťovanského", "Bažantia", "Bedľová", "Belanská",
    "Belehradská", "Bellova", "Benadova", "Bencúrova", "Benediktínska",
    "Beniakova", "Benkova", "Berlínska", "Bernatovská", "Bernolákova",
    "Berzeviczyho", "Beskydská", "Betliarska", "Bezručova", "Bežecká",
    "Biela", "Bielocerkevská", "Bielohorská", "Bielych albatrosov", "Bktanická záhrada",
    "Blatná", "Blesková", "Bocatiova", "Bogoľ", "Borievková",
    "Borodáčova", "Borovicová", "Bosákova", "Botanická záhrada", "Bottova",
    "Bočná", "Branisková", "Bratislavská", "Brestová", "Breziny",
    "Breznianska", "Brezová", "Brečtanová", "Brigádnická", "Brnenská",
    "Brodná", "Bronzová", "Bruselská", "Brusnicová", "Budanová",
    "Budapeštianska", "Budovateľská", "Bukovecká", "Buková", "Bukureštská",
    "Bulharská", "Buzinská", "Buzulucká", "Bystrická", "Bytový podnik mesta Košice",
    "CVČ Domino", "Cesta do Hanisky", "Cesta pod Hradovou", "Cezmínová", "Chalupkova",
    "Charkovská", "Chmeľníky", "Chrastie", "Chrómová", "Cikkerova",
    "Cimborkova", "Cintorínska", "Cirbusovej", "Clementisova", "Cottbuská",
    "Cyklistická", "Cyprusová", "Czambelova", "Cédrová", "Cínová",
    "Darg. hrdinov, Miestny úrad", "Dargovská", "Detvianska", "Diamantová", "Dneperská",
    "Dobšinského", "Dolina", "Dom umenia", "Dominikánske námestie", "Domčeková",
    "Donská", "Dopravná", "Dopravný podnik mesta Košice", "Dr. Kostlivého", "Drabova",
    "Drevný trh", "Drieňová", "Drocarov park", "Drozdia", "Družicová",
    "Družstevná", "Dubová", "Dulová", "Dunajská", "Dvorkinova",
    "Dénešova", "Dúbravská", "Dúhová", "EcoPoint", "Edisonova",
    "Európska trieda", "Exnárova", "Fakľová", "Fatranská", "Fejova",
    "Feketeova pažiť", "Festivalové námestie", "Fialková", "Fibichova", "Floriánska",
    "Franckova", "Františkánska", "Furčianska", "Fábryho", "Fándlyho",
    "Gagarinovo námestie", "Galaktická", "Galgovecká", "Garbiarska", "Gavlovičova",
    "Gazdovská", "Gaštanová", "Gelnická", "Gemerská", "Gerlachovská",
    "Goetheho", "Gogoľova", "Goldírova", "Golianova", "Gorkého",
    "Gorovecká", "Grešákova", "Grófska", "Gudernova", "Gymnázium Opatovská",
    "Haburská", "Halmiho dvor", "Hanojská", "Harmančeková", "Harmincova",
    "Harčarova", "Havanská", "Haviarska", "Havlíčkova", "Hellova",
    "Helsinská", "Hemerkova", "Herlianska", "Heydukova", "Hečkova",
    "Hlavná", "Hlavná pošta", "Hlavné námestie", "Hlinkova", "Hlivová",
    "Hlohová", "Hodonínska", "Hollého", "Holubyho", "Horná",
    "Hornádska", "Horolezecká", "Horovova", "Hrabová", "Hradbová",
    "Hraničná", "Hrbová", "Hrebendova", "Hriešny - Mravenisko", "Hrnčiarska",
    "Hroncova", "Hronská", "Hríbová", "Humenská", "Huncovská",
    "Hurbanova", "Husárska", "Hutnícka", "Hviezdoslavova", "Hájnická",
    "Hájska", "Húskova", "Idanská", "Inovecká", "Inžinierska",
    "Ipeľská", "Irkutská", "Jabloňová", "Jahodová", "Jakabov palác",
    "Jakobyho", "Jaltská", "Janigova", "Janitorova", "Jantárová",
    "Jantárové námestie", "Jarabinová", "Jarková", "Jarmočná", "Jarná",
    "Jaseňová", "Jasovská", "Jasuschova", "Javorová", "Jazdecká",
    "Jazerná", "Jazmínová", "Jazvečia", "Jačmenná", "Jedlíkova",
    "Jedľová", "Jegorovovo námestie", "Jelenia", "Jelšavská", "Jelšová",
    "Jenisejská", "Jesenná", "Jesenského", "Jihlavská", "Jilemnického",
    "Jiskrova", "Juhoslovanská", "Junácka", "Južná trieda", "Južné nábrežie",
    "Jána Pavla II.", "Jánošíkova", "K Hutke", "K Zoologickej záhrade", "K ihrisku",
    "K lesu", "K letisku", "K majeru", "KVP, kláštor", "Kadlubská",
    "Kalinovská", "Kalinčiakova", "Kameničná", "Kamenná", "Kapustná",
    "Karlovarská", "Karmelitánska", "Karpatská", "Kaspická", "Kasárenské námestie",
    "Katastrálny urad", "Katkin park", "Kavečianska cesta", "Kaštieľna", "Keldišova",
    "Kertésova", "Kežmarská", "Kino Družba", "Kisdyho", "Kladenská",
    "Klimkovičova", "Klinčeková", "Kmeťova", "Kolibár", "Komenského",
    "Komenského park", "Konečná", "Konopná", "Konvalinková", "Koník",
    "Končistá", "Kopečná", "Korýtková", "Kosatcová", "Kostolianska cesta",
    "Kostolná", "Kostrova", "Kovaľská", "Kováčska", "Kozáková",
    "Košice, AS", "Košice, Šaca, Benzinol", "Košťova", "Kpt. Jaroša", "Kpt. Nálepku",
    "Krajná", "Krajský súd", "Krakovská", "Krasinského", "Krematórium",
    "Kremnická", "Krivá", "Križinova", "Krmanova", "Krompašská",
    "Krosnianska", "Kruhový objazd, Alejová", "Kruhový objazd, Moldavská", "Kruhový objazd, Tr. SNP", "Krupinská",
    "Králičia", "Krásnohorská", "Krátka", "Krčméryho", "Ku Bangortu",
    "Ku Gardu", "Ku Gederu", "Ku hájovni", "Ku mlynu", "Ku potoku",
    "Ku štrkovisku", "Kubíková", "Kukuričná", "Kukučínova", "Kupeckého",
    "Kurská", "Kustrova", "Kuzmányho", "Kvetná", "Kysucká",
    "Kórejská", "Laborecká", "Lackova", "Ladožská", "Lechkého",
    "Lermontovova", "Lesná", "Lesnícka", "Letecká", "Letisko",
    "Letná", "Levanduľová", "Levická", "Levočská", "Lichardova",
    "Lidické námestie", "Liesková", "Limbová", "Lingov", "Lipová",
    "Liptovská", "Lomená", "Lomnická", "Lomonosovova", "Londýnska",
    "Lorinčícka", "Lovecká", "Lubina", "Ludmanská", "Ludvíkov dvor",
    "Luník VIII", "Lupkovská", "Lučenecká", "Lyžiarska", "Löfflerova",
    "Lúčna", "Lúčnicová", "Macákova", "Madridská", "Magdalénska",
    "Magistrát mesta Košice", "Magnezitárska", "Magurská", "Maková", "Malinová",
    "Maloidanská", "Malokarpatská", "Malá", "Markušova", "Martinská",
    "Maršala Koneva", "Masarykova", "Matičná", "Matuškova", "Maurerova",
    "Maďarská", "Medená", "Medická", "Medzevská", "Medzi mostami",
    "Mengusovská", "Mestský park", "Meteorová", "Meškova", "Michalovská",
    "Mierová", "Mikovíniho", "Milosrdenstva", "Minská", "Miškovecká",
    "Mliečna", "Mlynská", "Mlynská bašta", "Mlynárska", "Mládežnícka",
    "Modranská", "Mojmírova", "Moldavská", "Moldavská cesta", "Moldavská, obchodné centrá",
    "Mongolská", "Moravská", "Mosadzná", "Moskovská trieda", "Moyzesova",
    "Mozartova", "Močiarna", "Moňok", "Mudroňova", "Murgašova",
    "Muránska", "Muškátová", "Myslavská", "Myslavská 87", "Májová",
    "Mánesova", "Mäsiarska", "Na Banisegu", "Na Brehu", "Na Demetri",
    "Na Furmanci", "Na Grunte", "Na Horke", "Na Kalvárii", "Na Kope",
    "Na Kope I", "Na Kope II", "Na Kope III", "Na Kope IV", "Na Kope IX",
    "Na Kope V", "Na Kope VI", "Na Kope VII", "Na Kope VIII", "Na Kope X",
    "Na Košarisku", "Na Polianku", "Na Rožku", "Na Záhumní", "Na doline",
    "Na hore", "Na hájiku", "Na močidlách", "Na pažiti", "Na prednom Záhumní",
    "Na sihoti", "Na stráni", "Na zadnom Záhumní", "Na Šajbe", "Nad Bangortami",
    "Nad Belogradom", "Nad záhradami", "Napájadlá", "Narcisová", "Nemessányiho",
    "Nerudova", "Nevädzová", "Nešporova", "Niklová", "Nitrianska",
    "Nivky", "Nižná úvrať", "Nižné Chmeľníky", "Nižné Kapustníky", "Nižný Heringeš",
    "Novobanská", "Nová", "Nová nemocnica", "Nábrežná", "Nám. Sv Cyrila a Metoda",
    "Námestie Košických mučeníkov", "Námestie L. Novomeského", "Námestie Maratónu mieru", "Námestie Oceliarov", "Námestie kozmonautov",
    "Námestie maratónu mieru", "Námestie mladých poľnohospodárov", "Námestie osloboditeľov", "Námestie slobody", "Námestie sv. Vavrinca",
    "Národná trieda", "Národné námestie", "Němcovej", "OC Optima, dolný vstup", "Obchodná",
    "Obchodná akadémia", "Oblá", "Obrancov mieru", "Obrody", "Ochotnícka",
    "Odborárska", "Okresný úrad", "Olivová", "Omská", "Ondavská",
    "Opatovská", "Opatovská cesta", "Opálová", "Opátska", "Oravská",
    "Orechová", "Orgovánová", "Orlia", "Orná", "Ortoviská",
    "Ortvaňová", "Osiková", "Osloboditeľov", "Ostravská", "Ostrovského",
    "Ovocná", "Ovručská", "Ovsená", "Oštepová", "Pajorova",
    "Palackého", "Palkovičova", "Palmová", "Palárikova", "Panelová",
    "Papradia", "Park Angelinum", "Park duklianskych obetí", "Park mládeže", "Park obrancov mieru",
    "Partizánska", "Pasienková", "Pasteurova", "Pasteurovo námestie", "Pasáž Valentina",
    "Paulínyho", "Pažitná", "Pekinská", "Pekná", "Perešská",
    "Perlová", "Petzvalova", "Pezinská", "Pieninská", "Piesočná",
    "Piešťanská", "Platanová", "Platinová", "Plzenská", "Plávková",
    "Plťová", "Pod Furčou", "Pod Gruntom", "Pod Hájmi", "Pod Stavencom",
    "Pod Vitalinou", "Pod horou", "Pod hrabinou", "Pod hrebienkom", "Pod kaštieľom",
    "Pod lesom", "Pod vinicami", "Pod vlekom", "Pod Čapášom", "Pod šiancom",
    "Podbeľová", "Podjavorinskej", "Podkamenná", "Podnikateľská", "Podtatranského",
    "Pokojná", "Pokroku", "Polesná", "Polianska", "Poliklinika Východ",
    "Pollova", "Poloninská", "Poludníková", "Polárna", "Poničanova",
    "Popod vlek", "Popradská", "Postupimská", "Potočná", "Považská",
    "Považská, Nová nemocnica", "Povrazová", "Povstania českého ľudu", "Poľná", "Poľovnícka",
    "Poľovská", "Poľská", "Pošta 2", "Poštová", "Požiarnická",
    "Prasličková", "Prašná", "Pražská", "Prešovská cesta", "Pri Hornáde",
    "Pri Hrušove", "Pri Krásnej", "Pri Miklušovej väznici", "Pri Teleku", "Pri bitúnku",
    "Pri hati", "Pri jazdiarni", "Pri letisku", "Pri nemocnici", "Pri plavárni",
    "Pri plynárni", "Pri pošte", "Pri prachárni", "Pri salaši", "Pri studničke",
    "Pri sídlisku", "Pri vagovni", "Pri železničnej stanici", "Pribinova", "Priemyselná",
    "Prievidzská", "Prof. Jána Kňazovického", "Protifašistických bojovníkov", "Prvosienková", "Príkra",
    "Prúdová", "Puškinova", "Pytliacka", "Púchovská", "Púpavová",
    "Pšeničná", "Radlinského", "Radnica Starého mesta", "Raketová", "Rampová",
    "Ranná", "Rastislavova", "Račianska", "Račí potok", "Ražná",
    "Rehoľná", "Repná", "Repíková", "Revúcka", "Rešov Majer",
    "Rešov majer", "Riznerova", "Robotnícka", "Rokycká", "Rooseveltova",
    "Rosná", "Rovníková", "Rozmarínová", "Rozvojová", "Rozálska",
    "Roľnícka", "Rožňavská", "Rubínová", "Rulandská", "Rumanova",
    "Rumunská", "Rusnákova", "Rušňové depo", "Ružomberská", "Ružová",
    "Ružová, OC Galéria", "Ružínska", "Ryba", "Rybárska", "Rázusova",
    "Rímska", "SOŠ automobilová", "Sabinovská", "Sadovnícka", "Senný trh",
    "Severné nábrežie", "Sečovská", "Sečovská cesta", "Skalická", "Skalná",
    "Skautská", "Skladná", "Sklepárska", "Slanecká", "Slavkovská",
    "Sliačska", "Slivník", "Slnečnicová", "Slnečná", "Slobody",
    "Slovenskej jednoty", "Slovenská", "Slovenská č. 20", "Slovenská č. 42", "Slovenského",
    "Sluková", "Sládkovičova", "Slávičia", "Smaragdová", "Smetanova",
    "Smreková", "Smutná", "Snežienková", "Sofijská", "Sokolovská",
    "Spišské námestie", "Spoločenský pavilón", "Sputniková", "Srbská", "Srnčia",
    "Staničná", "Staničné námestie", "Staroslovanská", "Starozagorská", "Stará baštová",
    "Stará prešovská", "Stará spišská cesta", "Starý Ťahanovský tunel", "Stierova", "Stodolova",
    "Stokrásková", "Strakova", "Strieborná", "Strmá", "Strojárenská",
    "Stromová", "Stropkovská", "Strážna", "Strážovská", "Studničná",
    "Stálicová", "Suchodolinská", "Sv. Gorazda", "Sv. Ladislava", "Svetlá",
    "Svetlá Pusta", "Svidnícka", "Svornosti", "Svätej rodiny", "Svätoplukova",
    "Svätovavrinecká", "Szabadosova", "Szakkayho", "Súľovská", "Tajovského",
    "Talinská", "Tatarkova", "Tatranská", "Technická univerzita", "Teplárenská",
    "Tepláreň", "Teplého", "Terchovská", "Teslova", "Textilná",
    "Tešedíkova", "Thurzova", "Tibavská", "Tichá", "Tigria",
    "Timonova", "Timravy", "Titogradská", "Titánová", "Tokajská",
    "Tokajícka", "Tolstého", "Tomášikova", "Topoľová", "Topoľčianska",
    "Topásová", "Toryská", "Továrenská", "Tramínová", "Tranovského",
    "Traverz 2", "Traťová", "Trebišovská", "Trenčianska", "Tri hôrky",
    "Trieda KVP", "Trieda Košického vládneho programu", "Trieda SNP", "Trieda arm. gen. Svobodu", "Trnavská",
    "Trnková", "Trolejbusová", "Turgenevova", "Turistická", "Turnianska",
    "Tučkova", "Tvrdošínska", "Tyršovo nábrežie", "Táborská", "Tŕňová",
    "Uherova", "Ukrajinská", "Ul. Sv. Ladislava", "Ulica Sajkov", "Ulica osloboditeľov",
    "Univerzitná", "Uralská", "Urbánkova", "Urbárska", "Uršulínska",
    "Učňovská", "Užhorodská", "V úvoze", "VSS križovatka", "VSS, križovatka",
    "Vajanského", "Valalická", "Valeo", "Varšavská", "Važecká",
    "Vencová", "Veterná", "Viedenská", "Vihorlatská", "Viničná",
    "Vitézov dvor", "Višňová", "Vnútorný Červený breh", "Vo výmoli", "Vodná",
    "Vodomeračská", "Vodárenská", "Vojenská", "Vojvodská", "Vonkajší Červený breh",
    "Vozárova", "Vrabčia", "Vranovská", "Vrchná", "Vrátna",
    "Vstupný areál", "Vstupný areál U.S. Steel", "Vtáčí chodník", "Vyhoňská", "Vysokoškolská",
    "Vyšná", "Vyšná úvrať", "Vyšný dvor", "Vínna", "Vínová",
    "Východná", "Výstavby", "Včelárska paseka", "Vŕbová", "Watsonova",
    "Werferova", "Wuppertálska", "Wurmova", "Za amfiteátrom", "Za dolným mlynom",
    "Za mostom", "Za priekopou", "Za školou", "Za štadiónom", "Zajačia",
    "Zborovjanova", "Zborovská", "Zbrojničná", "Zeleninárska", "Zelená",
    "Zelená stráň", "Zelený dvor", "Zemianska", "Zemplínska", "Zichyho",
    "Zimná", "Zinková", "Zlatá", "Zoborská", "Zombova",
    "Zupkova", "Zuzkin park", "Zvolenská", "Zvonárska", "Zvončeková",
    "Záborského", "Zádielska", "Záhrada Bernátovce", "Záhradná", "Zámočnícka",
    "odpočívadlo Valaliky", "Ázijská trieda", "Úzka", "Čajakova", "Čajkovského",
    "Čapajevova", "Čechovova", "Čerešňová", "Čergovská", "Čermeľ",
    "Čermeľská cesta", "Čermeľské prielohy", "Čermeľské údolie", "Červený breh - Dual Slalom", "Červený rak",
    "Československej armády", "Československého odboja", "Česká", "Čiernomorská", "Čingovská",
    "Čičky-majer", "Čkalovova", "Člnková", "Čordákova", "Čárskeho",
    "Čínska", "Ďatelinová", "Ďumbierska", "Ľanová", "Ľubovnianska",
    "Ľudová", "Šaca, námestie", "Šafranová", "Šafárikova trieda", "Šalviová",
    "Šamborská", "Šarišská", "Šebastovská", "Šemšianska", "Šipkova",
    "Široká", "Školská", "Školy pre telesne postihnutých", "Škovránčia", "Škultétyho",
    "Šoltésovej", "Športová", "Šrobárova", "Štefánikova", "Štiavnická",
    "Štrbská", "Štrková", "Študentská", "Štítová", "Štúrova",
    "Šuhajova", "Ťahanovská", "Ťahanovské riadky", "Žarnovická", "Žatevná",
    "Ždiarska", "Železiarenská", "Železničná", "Železničná nemocnica", "Železníky",
    "Železníky, križovatka", "Želiarska", "Žiacka", "Žilinská", "Žitná",
    "Žižkova", "Žriedlová", "Žľaby",
  ],
  "Malacky": [
    "1. mája", "Agátová", "Alojza Veselého", "Banarka - enduro", "Bernolákova",
    "Boreckého", "Boženy Nemcovej", "Brezová", "Brnianska", "Budovateľská",
    "Břeclavská", "Cesta mládeže", "D. Skuteckého", "Dielenská", "Družstevná",
    "Dubovského", "Duklianskych hrdinov", "Džbankáreň", "Ernsta Wiesnera", "F. Malovaného",
    "Ferdiša Kostku", "Gaštanová", "Hlboká", "Hodžova", "Hurbanova",
    "Hviezdoslavova", "Ivana Dérera", "J. Kráľa", "Janka Kráľa", "Javorová",
    "Jelšová", "Jesenského", "Jozefa Gabčíka", "Jozefa Kubinu", "Jozefa Murgaša",
    "Jána Hollého", "Jána Kalinčiaka", "Jána Kollára", "Jánošíkova", "Kalista Orgoňa",
    "Karola Virsíka", "Kláštorné námestie", "Kozia", "Krátka", "Kukorelliho",
    "Kukučínova", "L. Novomeského", "Legionárska", "Lesná", "Lipová",
    "Ludwiga Angerera", "Malacky", "Malacky, Žel. stanica", "Malé námestie", "Mansueta Olšovského",
    "Martina Benku", "Martina Rázusa", "Michala Tillnera", "Mierové námestie", "Mirka Nešpora",
    "Mlynská", "Mojmírova", "Na Brehu", "Na brehu", "Na majeri",
    "Na píle", "Nad výhonom", "Nová", "Nádražná", "Námestie SNP",
    "Námestie u Severínka", "Olšiny", "Oslobodenia", "Ota Kožucha", "Partizánska",
    "Pavla Blahu", "Pavla Hallona", "Petra Jilemnického", "Petra Straku", "Pezinská",
    "Poľná", "Pri Maline", "Pribinova", "Priemyselná", "Príjazdná",
    "Písniky", "Radlinského", "Rakárenská", "Rastislavova", "Robotnícka",
    "Rudolfa Dilonga", "Sadová", "Sama Chalupku", "Sasinkova", "Slovenská",
    "Sládkovičova", "Spojnica", "Stromová", "Stupavská", "Svätoplukova",
    "Tichá", "Továrenská", "Táborisko", "V. Clementisa", "Vajanského",
    "Vendelína J. Kučeru", "Veľkomoravská", "Vlastenecká", "Vysoká", "Vševlada Gajdoša",
    "Záhorácka", "Záhradna", "Záhradná", "Zámocká", "arm. gen. L. Svobodu",
    "gen. M. R. Štefánika", "kpt. Miloša Uhra", "Ľuda Zúbka", "Ľudovíta Fullu", "Šikmá",
    "Štefana Čulena", "Štúrova",
  ],
  "Michalovce": [
    "1. mája", "9. mája", "A. I. Dobrianskeho", "A. S. Makarenku", "A. S. Puškina",
    "A. V. Suvorova", "Agátová", "Alex. Markuša", "Andreja Hrehovčíka", "Andreja Kmeťa",
    "Andreja Sládkoviča", "Andreja Šándora", "Ant. Bernoláka", "Astrová", "Bieloruská",
    "Borovicová", "Boženy Nemcovej", "Brestová", "Brezová", "Cyrila a Metoda",
    "Dlhý rad", "Dr. Vlada Clementisa", "Duklianska", "Eda Urxa", "Elektrárenská",
    "Farská", "Ferdinanda Alexu", "Fialková", "Fr. Kráľa", "Františka Hečku",
    "Františka Kubača", "Garbiarska", "Gen. Petrova", "Gorazda Zvonického", "Gorazdova",
    "Grófa Antala Sztárayho", "Hrnčiarska", "Hrádok", "Humenská cesta", "Ivana Krasku",
    "J. A. Gagarina", "J. Barča-Ivana", "J. Bottu", "J. Fándlyho", "J. G. Tajovského",
    "J. I. Bajzu", "J. Murgaša", "J. Ľ. Holubyho", "Jana A. Komenského", "Janka Alexyho",
    "Janka Borodáča", "Janka Matúšku", "Jarná", "Jaroslawská", "Jedľová",
    "Jonáša Záborského", "Juraja Jánošíka", "Juraja Palkoviča", "Jána Hollého", "Jána Jessenia",
    "Jána Kalinčiaka", "Jána Kollára", "Jána Kostru", "Jána Palárika", "Jána Švermu",
    "Kamenárska", "Kapušianska", "Karola Kuzmányho", "Kavarnianska", "Klobučnícka",
    "Koceľova", "Konečná", "Kostolné námestie", "Kpt. Nálepku", "Krymská",
    "Krásnovská", "Krátka", "Kyjevská", "L. N. Tolstého", "Laca Novomeského",
    "Lastomírska", "Leningradská", "Letná", "Liesková", "Lipová",
    "Lúčna", "M. I. Kutuzova", "Margarétová", "Martina Benku", "Martina Kukučína",
    "Martina Rázusa", "Masarykova", "Maxima Gorkého", "Meďovská", "Michala Bónu",
    "Michala Slávika", "Mik. Aleša", "Mikuláša Gerbu", "Mikuláša Kopernika", "Miloša Uhra",
    "Minská", "Mirka Nešporu", "Mlynská", "Mojmírova", "Moldavská",
    "Moskovská", "Močarianska", "Muškátová", "N. V. Gogoľa", "Nad Laborcom",
    "Narcisová", "Nábr. J. M. Hurbana", "Námestie Jána Pavla II.", "Námestie osloboditeľov", "Námestie slobody",
    "Obchodná", "Obrancov mieru", "Odbojárov", "Odeská", "Okružná",
    "P. I. Čajkovského", "P. J. Šafárika", "P. O. Hviezdoslava", "Partizánska", "Pasáž",
    "Pavla Horova", "Pekárenská", "Petra Jilemnického", "Plynárenská", "Pri mlyne",
    "Pri sýpke", "Pribinova", "Priemyselná", "Priemyselný park", "Prof. Hlaváča",
    "Púpavová", "Rastislavova", "Remeselnícka", "Ružová", "Rybárska",
    "S. H. Vajanského", "SNP", "Saleziánov", "Sama Chalupku", "Samova",
    "Samuela Tešedíka", "Samuela Tomášika", "Severná", "Sibírska", "Sklenárska",
    "Slovenská", "Smreková", "Sobranecká cesta", "Sosnová", "Staničná",
    "Starolaborecká", "Staré nábrežie", "Stavbárov", "Svornosti", "Svätoplukova",
    "T. J. Moussona", "Tehliarska", "Terézie Vansovej", "Tichá", "Timravy",
    "Topolianska", "Topoľová", "Továrenská", "Tulipánová", "Ukrajinská",
    "Ulica pri Duši", "Uralská", "Urnový háj", "Užhorodská", "V. I. Čapajeva",
    "Verbovčík", "Via Roma", "Vihorlatská", "Vila-Real", "Vinianska cesta",
    "Višňová", "Volgogradská", "Vrbovská", "Vyškovská", "Zakarpatská",
    "Zeleninárska", "Zemplínska", "Zvončeková", "Záhradná", "Úzka",
    "Čsl. armády", "Ľud. Kukorelliho", "Ľudovíta Pavla", "Ľudovíta Štúra", "Š. Kukuru",
    "Široká", "Školská", "Špitálska", "Športová", "Štefana Fidlíka",
    "Štefana Moyzesa", "Štefana Tučeka", "Štefánikova",
  ],
  "Poprad": [
    "1. mája", "29. augusta", "Allendeho", "Alžbetina", "Amurská",
    "Autovlak Poprad-Tatry", "Bajkalská", "Banícka", "Bernolákova", "Bezručova",
    "Bottova", "Boženy Němcovej", "Brežný riadok", "Brokoffova", "Budovateľská",
    "Bulharská", "Buzulucká", "Cesta k stavbe", "Chalupkova", "Cintorínska",
    "Dlhé hony", "Dolný rad", "Dominika Tatarku", "Donská", "Dostojevského",
    "Drevárska", "Družstevná", "Dubová", "Duklianska", "Fabiniova",
    "Farbiarska", "Francisciho", "Františka Hečku", "Fraňa Kráľa", "Gattingerova",
    "Gemerská", "Gerlachovská", "Gorkého", "Grossova", "Grébova",
    "Halatova", "Harmincova", "Hitschova", "Hlavná", "Hodžova",
    "Horská", "Hraničná", "Hurbanova", "Huszova", "Hviezdoslavova",
    "J. Tranovského", "Jabloňová", "Jahodná", "Janka Kráľa", "Jarmočná",
    "Jarná", "Jazzová", "Jedľová", "Jesenná", "Jesenského",
    "Jiřího Wolkera", "Jokaiho", "Joliota Curie", "Karpatská", "Kežmarská",
    "Kmeťova", "Kollárova", "Komenského", "Koperníkova", "Kopečná",
    "Košická", "Krompecherova", "Krátka", "Kukučínova", "Kuzmányho",
    "Kvetnica", "Kvetná", "Kysucká", "Lerchova", "Lesná",
    "Letná", "Levočská", "Lidická", "Lipová", "Liptovská",
    "Lomnická", "Ludvíka Svobodu", "Lúčna", "MPČĽ", "Magurská",
    "Majstra Pavla", "Majunkeho", "Malinovského", "Malinová", "Matejovská",
    "Matejovské námestie", "Mierová", "Mlynská", "Mládeže", "Mnoheľova",
    "Moyzesova", "Murgašova", "Na letisko", "Nad tehelňou", "Nemocničná",
    "Nerudova", "Nešporova", "Novomeského", "Nová", "Nové nábrežie",
    "Nábrežie Jána Pavla II.", "Námestie Mórica Beňovského", "Námestie svätého Egídia", "Odbojárska", "Okružná",
    "Oravská", "Orlická", "Palárikova", "Papierenská", "Partizánska",
    "Pavlovova", "Petra Jilemnického", "Pod bránou", "Podjavorinskej", "Podtatranská",
    "Poprad-Tatry TEŽ", "Popradskej brigády", "Popradské nábrežie", "Potočná", "Poľná",
    "Prešovská", "Priemyselná", "Priemyselný areál", "Puškinova", "Radničná",
    "Rastislavova", "Reinerova", "Richarda Bekessa", "Riečna", "Rovná",
    "Rázusova", "Sadová", "Scherfelova", "Schmoerova", "Scholtzova",
    "Skladová", "Slavkovská", "Slnečná", "Slobody", "Slov. Nár. Povstania",
    "Slovenského odboja", "Sládkovičova", "Smetanova", "Sobotská", "Sobotské námestie",
    "Sokolovská", "Spišská", "Staničná", "Staré ihrisko", "Stavbárska",
    "Strážske námestie", "Suchoňova", "Sv. Juraja", "Svitská cesta", "Svätoplukova",
    "Svätého Mateja", "Tajovského", "Tatranská", "Tatranské námestie", "Tehelňa",
    "Tekovská", "Teplická cesta", "Terézie Vansovej", "Tolstého", "Tomášikova",
    "Továrenská", "Továrenská štvrť", "Traktorová", "Trhová", "Uherova",
    "Uralská", "Vagonárska", "Vajanského", "Velická cesta", "Velické námestie",
    "Vodárenská", "Wallachyova", "Zdravotnícka", "Zemplínska", "Zimná",
    "Záborského", "Záhradnícka", "Ústecko-Orlická", "Úzka", "Šafárikova",
    "Šarišská", "Široká", "Škultétyho", "Šoltésovej", "Športová",
    "Šrobárova", "Štefánikova", "Štefánska", "Štúrova", "Švermova",
    "Železničná",
  ],
  "Rimavská Sobota": [
    "A. Markuša", "Agátová", "B. Bartóka", "Bakulínyho", "Bokorová pust.",
    "Bottova", "Cestárska", "Cintorínska", "Cukrovarská", "Daxnerova",
    "Dostojevského", "Dr. V. Clementisa", "Družstevná", "Dukel. hrdinov", "Dúžavská cesta",
    "E. Putru", "Francisciho", "Fučíkova", "Gaštanová", "Gorkého",
    "Hlavné námestie", "Hurbanova", "Hviezdoslavova", "I. Hatvaniho", "J. Bodona",
    "J. Fábryho", "J. Kráľa", "Jabloňová", "Jarná", "Javorová",
    "Jesenského", "Jánošíkova", "K. Mikszátha", "Kirejevská", "Kolínska",
    "Konvalinková", "Košická cesta", "Kpt. Šmála", "Krajná", "Kraskova",
    "Kubányho", "Kuzmányho", "Kvetná", "Kúpeľná", "Kľačany",
    "L. Novomeského", "L. Svobodu", "Lesná", "Letná", "Liesková",
    "Lipová", "Malinová", "Malohontská", "Malá", "Mestská záhrada",
    "Milana Rastislava Štefánika", "Mlynská", "Mládeže", "Most lásky", "Na Chrenovisku",
    "Narcisová", "Nezábudková", "Novosadská", "Nová", "Námestie M. Tompu",
    "Námestie Š. M. Daxnera", "Odborárska", "Okružná", "Orgovánová", "P. Dobšinského",
    "P. Hostinského", "Pavla Jozefa Šafárika", "Pivovarská", "Podjavorinskej", "Pokoradzká",
    "Por. Ušiaka", "Potravinárska", "Povstania", "Púpavová", "Rimavská",
    "Rožňavská", "Ružová", "Rybárska", "S. Kollára", "Sabová",
    "Salvova", "Sedliacka", "Slnečná", "Sobôtka", "Stavbárov",
    "Svätoplukova", "Sídlisko Rimava", "Sütö pustatina", "T. Vansovej", "Tehlová",
    "Tolstého", "Tomašovská", "Tompova", "Tomášikova", "Tormáš",
    "Trhové námestie", "Tržná", "Tulipánová", "Valach. pust.", "Veterná",
    "Vinice", "Včelinec", "Záhradnícka", "Čerenčianska", "Čerešňová",
    "Česká", "Šamarianka", "Šibeničný vrch", "Školská", "Škultétyho",
    "Športová", "Šrobárova", "Štadion", "Šári pustatina", "Železničiarska",
    "Železničná", "Žánovská",
  ],
  "Senec": [
    "A. Dubčeka", "A. Hlinku", "Agátová", "Andreja Sládkoviča", "Aurela Stodolu",
    "Baničova", "Bazová", "Bernolákova", "Boldocká cesta", "Borievková",
    "Borovicová", "Bratislavská", "Brezová", "Bélu Bartóka", "Chalupkova",
    "Diaľničná cesta", "Dlhá", "Dobšinského", "Dolná", "Drienková",
    "Drozdia", "Dúhová", "Emila Boleslava Lukáča", "Farské námestie", "Fialková",
    "Fraňa Kráľa", "Fučíkova", "Fándlyho", "Gagarinova", "Gaštanová",
    "Hany Zelinovej", "Helios I pasáž", "Helios pasáž I", "Hečkova", "Hollého",
    "Holubia", "Horná", "Horný dvor", "Hurbanova", "Hviezdoslavova",
    "Inovecká", "J. Csermáka", "J. Farkasa", "J. G. Tajovského", "J. Jesenského",
    "J. Murgaša", "Jarná", "Jasná", "Jastrabia", "Javorová",
    "Jedľová", "Jesenná", "Jána Smreka", "Jánošíkova", "Kalinčiakova",
    "Kapria", "Karasová", "Karola Šišku", "Kollárova", "Kováčska",
    "Košická", "Krátka", "Kvetná", "Kysucká", "Lastovičia",
    "Lesná", "Letná", "Lichnerova", "Lipová", "Liptovská",
    "Lúčna", "M. Urbana", "Marhuľová", "Mesačná", "Mierové námestie",
    "Mlynská", "Morušová", "Moyzesova", "Muškátová", "Mäsiarska",
    "Nitrianska", "Novomeského", "Námestie 1. mája", "Námestie Alberta Molnára", "Okružná",
    "Oravská", "Orechová", "Pezinská", "Pivničná", "Pod vinicami",
    "Považská", "Poľná", "Pri Búroši", "Pri Striebornom jazere", "Pri včelárikoch",
    "Pri Čiernej vode", "Pri Štifte", "Pribinova", "Priemyselná", "Recká cesta",
    "Robotnícka", "Rosná", "Ružová", "Rybárska", "SNP",
    "Sadová", "Senec námestie", "Senecká", "Sereďská", "Slnečná",
    "Slnečné jazerá", "Slávičia", "Smreková", "Sokolská", "Sovia",
    "Stavbárska", "Strmá", "Svätoplukova", "Svätého Urbana", "Tehelná",
    "Trhovisko Martex", "Trnavská", "Trnková", "Tulipánová", "Turecká",
    "Turnianska", "Vajanského", "Vinohradnícka", "Višňová", "Vodná",
    "Vrabčia", "Vrbenského", "Vtáčia", "Zemplínska", "Zimná",
    "Záhradnícka", "Čerešňová", "Ľudovíta Fullu", "Šafárikova", "Šamorínska",
    "Školská", "Škorcová", "Škovránčia", "Športová", "Štefánikova",
    "Štúrova", "Šípková", "Žarnovova", "Železničná", "Žitavská",
  ],
  "Zvolen": [
    "1. mája", "11. marca", "29. augusta", "9. mája", "A. Bernoláka",
    "A. Hlinku", "A. Sládkoviča", "Alexandra Nográdyho", "Bakova Jama", "Balkán",
    "Bela IV.", "Borovianska", "Boženy Němcovej", "Bratov Veselovcov", "Brezová",
    "Buková", "Buzulucká", "Bystrický rad", "Centrum", "Cesta ku Continentalu",
    "Chodník slávy", "Daniela Ertla", "Dekréta Matejovie", "Divadelná", "Dobronivská cesta",
    "Dolná kolónia", "Družstevná", "Dubová", "Dukelských hrdinov", "E. M. Šoltésovej",
    "Elektrárenská", "Evgenija Pavloviča Voljanského", "F. Hečku", "F. Kráľa", "Ferjenčíkova",
    "Fialková", "Francisciho", "Gaštanová", "Generála Asmolova", "Generála Svobodu",
    "Hať Podharajch", "Hlbiny", "Hrnčiarska", "Hronská", "Hurbanova",
    "I. Krasku", "Imatra", "J. A. Komenského", "J. Alexyho", "J. Bottu",
    "J. Bánika", "J. C. Hronského", "J. Donča", "J. G. Tajovského", "J. Hollého",
    "J. Jesenského", "J. Kalinčiaka", "J. Kráľa", "J. Matušku", "J. Nerudu",
    "J. Švermu", "Jabloňová", "Jaselská", "Jaseňová", "Javorová",
    "Jazmínová", "Jedľová", "Jozefa Kozáčeka", "Juraja Fándlyho", "Juraja Jánošíka",
    "Jurija Gagarina", "Jána Jiskru", "Jána Kollára", "Jána Poničana", "Karola Šmidkeho",
    "Kimovská", "Kremnická", "Krupinská cesta", "Kráľová", "Kubániho",
    "Kuzmányho nábrežie", "L. Novomeského", "Lesnícka", "Lieskovská cesta", "Lihoveckého",
    "Lipová", "Lukovská cesta", "Lukovské úhrady", "Lučenecká cesta", "Lúčna",
    "M. Bazovského", "M. Kukučína", "M. M. Hodžu", "M. Nešpora", "M. R. Štefánika",
    "M. Rázusa", "MDD", "Maršála Malinovského", "Mateja Bela", "Mládežnícka",
    "Mojmírova", "Môťovská cesta", "Môťovská ulica", "Na Hrádok", "Na Hôrke",
    "Na Rovni", "Na Štepnici", "Nad kasárňami", "Nad mlynom", "Neresnická Cesta",
    "Neresnická cesta", "Nevädzová", "Nezábudková", "Nižovec", "Novozámocká",
    "Nábrežie", "Nádvorná", "Námestie Cyrila a Metoda", "Námestie Mládeže", "Námestie SNP",
    "Námestie slobody", "Obchodná", "Obrancov mieru", "Okružná", "Orgovánová",
    "P. J. Šafárika", "P. Jilemnického", "P. O. Hviezdoslava", "Park zabudnutých susedov", "Partizánska",
    "Pod Dráhami", "Pod Holým brehom", "Pod vodojemom", "Podbeľová", "Podboroviansky potok",
    "Povstaleckých letcov", "Prachatická", "Pražská", "Predmestie", "Pribinova",
    "Pustý Hrad", "Púpavová", "R. Jašíka", "R. Čelku", "Rastislavova",
    "Rivnianska", "Ružová", "Rákoš", "S. Chalupku", "Sekierska dolina",
    "Severná", "Slatinské nábrežie", "Slnečná", "Smreková", "Snežienková",
    "Sokolie skaly", "Sokolská", "Somolického", "Sosnová", "Strakonická cesta",
    "Stráž", "Strážska cesta", "Svätoplukova", "T. G. Masaryka", "T. Vansovej",
    "Tehelná", "Tomášikova", "Topoľová", "Trhová", "Trňanská",
    "Tulipánová", "Tulská", "Unionka", "Uramova", "Viliama Paulínyho Tótha",
    "Zolnianska", "Záhonok", "Ľ. Fullu", "Ľ. Medveckého", "Ľ. Podjavorinskej",
    "Ľ. Štúra", "Š. Moyzesa", "Š. Višňovského", "Školská", "Študentská",
    "Železničná",
  ],
  "Žilina": [
    "1. mája", "9. mája", "Agátová", "Alexandra Rudnaya", "Alexyho",
    "Ambra Pietra", "Ametystová", "Andreja Kmeťa", "Andreja Lemeša", "Andreja Žarnova",
    "Antona Bernoláka", "Antona Bielka", "Antona Petrovského", "Antonína Milfaita", "Astrová",
    "Azúrová", "B. Němcovej", "B. S. Timravy", "Bagarova", "Bajzova",
    "Baničova", "Banícka", "Belajov dvor", "Belicová", "Benjamína Martinského",
    "Berlínska", "Berylová", "Bezručova", "Biela", "Bitarovská cesta",
    "Blankytná", "Bláhova", "Boncova", "Bordová", "Borová",
    "Bottova", "Bočná", "Bratislavská", "Brezová", "Brodek",
    "Brodňanov dvor", "Brodňanská", "Budatínska", "Bukovinská", "Bulharská",
    "Burianova Medzierka", "Burianova medzierka", "Bystrická", "Bytčianska", "Bytčická",
    "Bánovská cesta", "Béžová", "Bôrická cesta", "Centrálna", "Cesta k Paľovej búde",
    "Cesta k vodojemu", "Cesta na záhumnie", "Cesta na štadión", "Cestárska", "Cezpoľná",
    "Chalupkova", "Chlmecké námestie", "Chotárna", "Cintorínska", "Czambelova",
    "Dadanova", "Daniela Dlabača", "Daniela Krmana", "Daxnerova", "Dedinská",
    "Dlhá", "Do Brezičia", "Do Brezníka", "Do Magúr", "Do Mažiarca",
    "Do Medzilužia", "Do Polí", "Do Rosiny", "Do Rovní", "Do Stošky",
    "Do Stávku", "Do parku", "Do toboliny", "Dobšinského", "Dolná",
    "Dolná Trnovská", "Dolné Rudiny", "Dolní", "Dolný val", "Dolová",
    "Drieňová", "Drozdia", "Druhá", "Družecká", "Družstevná",
    "Dubová", "Dunajská", "Dúbravy", "Eduarda Nécseya", "Egrešová",
    "Emanuela Fila", "Energetikov", "Essenská", "Estakáda", "Farská Ulička",
    "Farská ulička", "Farské schody", "Fatranská", "Fedora Ruppeldta", "Ferka Urbánka",
    "Festivalová", "Fialková", "Fialová", "Figurova", "Framborská",
    "Františka Novotného", "Františkánske schody", "Fraňa Mráza", "Furmanská cesta", "Gabajova",
    "Gabriela Povalu", "Gabčíkova", "Gavlovičova", "Gazdova", "Gaštanová",
    "Gemerská", "Gerlachovská", "Gogoľova", "Granátová", "Gulejova",
    "Halašova", "Hallonova", "Hanušákova", "Hattalova", "Hečkova",
    "Hlavná", "Hlavná cesta", "Hlavátková", "Hlboká cesta", "Hlinská",
    "Hnedá", "Hodžova", "Hollého", "Holubia", "Hore humnami",
    "Hore vŕškom", "Horná", "Horná Trnovská", "Hornádska", "Horní",
    "Horný val", "Horská", "Hričovská", "Hronská", "Hroznová",
    "Hruštiny", "Hyrovská", "Hálkova", "Hôrecká cesta", "Ipeľská",
    "J. M. Geromettu", "J. M. Hurbana", "J. Tombora", "Jabloňová", "Jalcová",
    "Janka Kráľa", "Janka Silana", "Jantárová", "Jarná", "Jaseňová",
    "Jastrabia", "Javorová", "Jazmínová", "Jašíkova", "Jaššov dvor",
    "Jedlíkova", "Jedľová", "Jesenského", "Jezuitská", "Jozefa Cígera Hronského",
    "Jozefa Vuruma", "Jura Hronca", "Juraja Fándlyho", "Juraja Papánka", "Juraja Sklenára",
    "Juraja Slottu", "Juraja Závodského", "Jána Kalinčiaka", "Jána Kovalíka", "Jána Milca",
    "Jána Mičicu", "Jána Reka", "Jána Vojtaššáka", "Jána Čajdu", "Jánošíkova",
    "K Lesu", "K Ploskovu", "K Rochovici", "K cintorínu", "K múzeu",
    "Kamenná", "Kapria", "Kapustná", "Karasová", "Karmínová",
    "Karola Kmeťku", "Karpatská", "Ke Kostelu", "Kempelenova", "Kladenská",
    "Klemensova", "Klimovské", "Koceľova", "Kollárova", "Kolmá",
    "Komenského", "Kopanice", "Kortinská", "Korzo", "Kostolná",
    "Košická", "Kožov dvor", "Kragujevská", "Kraskova", "Kristenovej",
    "Krátka", "Krátká", "Krížna", "Ku krížu", "Ku studienke",
    "Ku zvonici", "Ku škôlke", "Kubelíkova", "Kubov dvor", "Kubínska",
    "Kukučínova", "Kultúrna", "Kuzmányho", "Kvačalova", "Kvetná",
    "Kysucká", "Kálov", "Laborecká", "Labutia", "Ladiverova",
    "Legionárska", "Lenčova", "Lesná", "Lesní", "Letná",
    "Levanduľová", "Levočská", "Lichardova", "Liesková", "Lieňová",
    "Limbová", "Lipovecká", "Lipová", "Lipňová", "Lombardiniho",
    "Lúčna", "M. R. Štefánika", "M. Šinského", "Magočovská", "Majerská",
    "Majochova", "Majstra sveta", "Makovického", "Malinová", "Malá",
    "Mariánske námestie", "Martina Benku", "Martina Rázusa", "Martinská", "Martinčekova",
    "Mateja Bela", "Matice slovenskej", "Matuškova", "Matúša Kavca", "McDrive",
    "Medzi plotmi", "Medzierka", "Mesačná", "Mikovíniho", "Mikuláša Dohnányho",
    "Mikuláša Nigriniho", "Mila Urbana", "Minčolská", "Mládeže", "Mládežnícka",
    "Modrá", "Mojmírova", "Mojšova Lúčka", "Morušová", "Most cez Vážsku vodnú nádrž Hričov",
    "Mostná", "Mostová", "Moyzesova", "Mrvečkova", "Murgašova",
    "Mydlárska", "Mýtna", "Na Bárek", "Na Horevaží", "Na Hradisko",
    "Na Hôrke", "Na Majerisku", "Na Malý Diel", "Na Píska", "Na Rovniach",
    "Na Sihoti", "Na Slini", "Na Straník", "Na Stráni", "Na Tobolky",
    "Na Veľký Diel", "Na Záchrastí", "Na Záhumní", "Na Zápletí", "Na Závaží",
    "Na bráne", "Na chotári", "Na cintorín", "Na dolinu", "Na kopci",
    "Na lány", "Na priekope", "Na skotni", "Na stanicu", "Na starej hradskej",
    "Na stave", "Na vráta", "Na Úvozu", "Na Šefranici", "Nadskaličná",
    "Nanterská", "Nemocničná", "Nezvalova", "Nešporova", "Nitrianska",
    "Nižedvorská", "Nová", "Nový Domov", "Nábrežie Rajčianky", "Nábrežná",
    "Námestie Andreja Hlinku", "Námestie J. Borodáča", "Námestie Jána Pavla II.", "Námestie Vrbu a Wetzlera", "Námestie gen. M. R. Štefánika",
    "Námestie hrdinov", "Námestie mladosti", "Námestie obetí komunizmu", "Námestie požiarnikov", "Námestie sv. Jána Bosca",
    "Námestie Ľudovíta Fullu", "Námestie Žilinskej synody", "Národná", "Obchodná", "Obežná",
    "Oblúková", "Obvodová", "Oceliarska", "Ohradská", "Okrajová",
    "Okrová", "Ondavská", "Ondráškov dvor", "Oravská", "Orgovánová",
    "Orlík", "Orolská", "Orčiešová", "Osiková", "Oslobodenia",
    "Osloboditeľov", "Ostriežová", "Osvety", "Osíková", "Ovocinárska",
    "Ovsená", "Oškerdská cesta", "P. O. Hviezdoslava", "Palárikova", "Pavla Mudroňa",
    "Pažite", "Pekná", "Pernikárska", "Petzvalova", "Piata",
    "Pietna", "Piešťanská", "Pittsburgská", "Pivovarská", "Platanová",
    "Pltnícka", "Pod Adamovcom", "Pod Borím", "Pod Bukovinou", "Pod Dielce",
    "Pod Dúbravou", "Pod Grendel", "Pod Hradiskom", "Pod Hôrkou", "Pod Laščeky",
    "Pod Lesem", "Pod Skalkou", "Pod cintorínom", "Pod hliniskom", "Pod hájom",
    "Pod jarkom", "Pod majerom", "Pod sadom", "Pod univerzitou", "Pod vinicou",
    "Pod záhradkou", "Poddielna", "Podskaličná", "Polomská", "Pomocná",
    "Popperovská", "Popradská", "Potoky", "Potočná", "Považský Chlmec",
    "Poľná", "Poštová", "Požiarnická", "Pražská", "Predmestská",
    "Prešovská", "Pri Celulózke", "Pri Kysuci", "Pri Rajčianke", "Pri ihrisku",
    "Pri rieke", "Pribinova", "Priehradná", "Prielohy", "Prieložná",
    "Priemyselná", "Prvá", "Prúty", "Pstruhová", "Purpurová",
    "Pustá", "Puškinova", "Radlinského", "Radničná", "Radová",
    "Rajecká", "Rajecká, Solinky", "Rajčianska", "Rakové", "Rastislavova",
    "Repkovského", "Republiky", "Revolučná", "Richtárska", "Riečna",
    "Romualda Zaymusa", "Rondel", "Rosinská", "Rovniankova", "Roľnícka",
    "Rubínová", "Rudolfa Dilonga", "Ružová", "Rybné námestie", "Rybníky",
    "Révaiovská", "Sad SNP", "Sad na Studničkách", "Sadová", "Saleziánska",
    "Samuela Timona", "Sasinkova", "Scheerova", "Segnerova", "Severná",
    "Sirotárska", "Sivá", "Skotňa", "Skotňová", "Slavomírova",
    "Slepá", "Slnečnicová", "Slnečná", "Slnečné námestie", "Slovanská",
    "Slovenských dobrovoľníkov", "Sládkovičova", "Smaragdová", "Smreková", "Snežnická cesta",
    "Spojná", "Spojovací", "Stará dedina", "Stavbárska", "Stehličia",
    "Stodolova", "Stračia", "Strieborná", "Strážovská", "Stárkova",
    "Sugoňova", "Sumčia", "Suvorovova", "Sv. Bystríka", "Sv. Cyrila a Metoda",
    "Sv. Gorazda", "Sv. Svorada a Benedikta", "Svážná", "Svätoplukova", "T. Vansovej",
    "Tajovského", "Tatranská", "Tehelná", "Terasy", "Tichá",
    "Tolstého", "Tomáša Ružičku", "Topoľová", "Trenčianska", "Tretia",
    "Trnavská", "Trnovská medzierka", "Tulipánová", "Tulská", "Tunel Žilina",
    "Tyrkysová", "U Hřiště", "Uhoľná", "Univerzitná", "Univerzitné námestie",
    "V Koutě", "Vajanského", "Variant v paragáne", "Varšavská", "Vavrinca Ottmayera",
    "Vendelína Javorku", "Veľkomoravská", "Veľká okružná", "Višňová", "Vojtecha Spanyola",
    "Vojtecha Tvrdého", "Vrania", "Vysokoškolákov", "Vysoká", "Vážska",
    "Za cintorínom", "Za kaštieľom", "Za kostolom", "Za plavárňou", "Za potokom",
    "Zadný dielec", "Zahradní", "Zaroháčovská", "Zelená", "Zvolenská",
    "Záborského", "Zábrehy", "Zábrežná", "Záchrastie", "Zádubanská",
    "Záhradná", "Záhradnícka", "Záhrbie", "Záhumenská", "Zámocká",
    "Západná", "Zástranská", "Závodská cesta", "Závoz", "Závozská",
    "Zúbekova", "Údolná", "Úhoria", "Ústecká", "Čajakova",
    "Čepiel", "Čerešňová", "Černovská", "Červená", "Čičkánikova",
    "Čulenova", "Čáklovská", "Ďatlia", "Ďurka Langsfelda", "Ľavobrežná",
    "Ľubľanská", "Šenkárovská", "Šibeničná", "Šiesta", "Školská",
    "Školský dvor", "Škorvánkov dvor", "Škultétyho", "Šoltésovej", "Športová",
    "Štaffenovský dvor", "Štefana Furdeka", "Štrková", "Študentská", "Štvrtá",
    "Štúrova", "Šťuková", "Železničná", "Žilinská", "Žitná",
    "Žltá",
  ],
};

// Locality → city mapping
const LOKALITA_TO_CITY: Record<string, string> = {
  "Bratislava I": "Bratislava",
  "Bratislava II": "Bratislava",
  "Bratislava III": "Bratislava",
  "Bratislava IV": "Bratislava",
  "Bratislava V": "Bratislava",
  "Košice I": "Košice",
  "Košice II": "Košice",
  "Košice III": "Košice",
  "Košice IV": "Košice",
  "Banská Bystrica": "Banská Bystrica",
  "Malacky": "Malacky",
  "Michalovce": "Michalovce",
  "Poprad": "Poprad",
  "Rimavská Sobota": "Rimavská Sobota",
  "Senec": "Senec",
  "Zvolen": "Zvolen",
  "Žilina": "Žilina",
};

function normalize(s: string): string {
  return s.toLowerCase()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s]/g, "")
    .trim();
}

export function searchStreets(query: string, lokalita?: string): StreetEntry[] {
  const q = normalize(query);
  if (q.length < 2) return [];

  // Determine which city to search
  let cityName = lokalita ? (LOKALITA_TO_CITY[lokalita] || lokalita) : "";
  let streets: string[] = [];
  let city = cityName;

  if (cityName && CITY_STREETS[cityName]) {
    streets = CITY_STREETS[cityName];
  } else {
    // Search all cities
    for (const [c, s] of Object.entries(CITY_STREETS)) {
      streets = streets.concat(s.map(st => st));
      // We need city info, so use different approach
    }
    // Fallback: search all
    const results: StreetEntry[] = [];
    const seen = new Set<string>();
    for (const [c, sts] of Object.entries(CITY_STREETS)) {
      for (const st of sts) {
        const norm = normalize(st);
        if (norm.startsWith(q) || norm.split(/\s+/).some(w => w.startsWith(q))) {
          const key = norm;
          if (!seen.has(key)) {
            seen.add(key);
            results.push({ street: st, lokalita: c, city: c });
          }
        }
      }
    }
    return results.slice(0, 8);
  }

  // Score results
  const scored: { entry: StreetEntry; score: number }[] = [];
  const seen = new Set<string>();
  for (const st of streets) {
    const norm = normalize(st);
    let score = 0;
    if (norm.startsWith(q)) score = 100;
    else if (norm.split(/\s+/).some(w => w.startsWith(q))) score = 80;
    else if (norm.includes(q)) score = 50;
    if (score > 0 && !seen.has(norm)) {
      seen.add(norm);
      scored.push({ entry: { street: st, lokalita: lokalita || city, city }, score });
    }
  }
  return scored.sort((a, b) => b.score - a.score).slice(0, 8).map(s => s.entry);
}
